services:
  postgres:
    image: postgres:17
    container_name: postgres_hitsclass
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=hits_class
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    image: 'ghcr.io/ivankobtsev/hits-class:latest'
    container_name: web_hitsclass
    restart: always
    depends_on:
      - postgres
    environment:
      - ConnectionStrings__DefaultConnection=Server=postgres;Database=hits_class;Port=5432;Username=postgres;Password=${POSTGRES_PASSWORD:-postgres};Pooling=true;Keepalive=5;Command Timeout=60
      - DefaultUser__Password=${DEFAULT_USER_PASSWORD:-admin123}
      - General__SiteUrl=${SITE_URL:-https://localhost}
      - Hangfire__EnableDashboard=false
      - TestApiEnabled=false
    volumes:
      - file_storage:/files:rw

  nginx:
    image: nginx:alpine
    container_name: nginx_hitsclass
    restart: always
    depends_on:
      - web
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ${SSL_CERT_PATH}:/etc/nginx/ssl/cert.pem:ro
      - ${SSL_KEY_PATH}:/etc/nginx/ssl/key.pem:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  postgres_data:
  file_storage:
