services:
  postgres:
    image: postgres:17
    container_name: postgres_hitsclass
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=hits_class
    ports:
      - '${POSTGRES_EXTERNAL_PORT:-5432}:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    image: 'ghcr.io/ivankobtsev/hits-class:latest'
    container_name: web_hitsclass
    restart: always
    depends_on:
      - postgres
    environment:
      - ConnectionStrings__DefaultConnection=Server=postgres;Database=hits_class;Port=5432;Username=postgres;Password=${POSTGRES_PASSWORD:-postgres};Pooling=true;Keepalive=5;Command Timeout=60
      - DefaultUser__Password=${DEFAULT_USER_PASSWORD:-admin123}
      - Hangfire__EnableDashboard=false
      - TestApiEnabled=false
    ports:
      - '${APP_PORT:-5000}:5000'
    volumes:
      - file_storage:/files:rw

volumes:
  postgres_data:
  file_storage:
