//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.20.0.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming
import * as Types from '../api-client.types';
import { useQuery, useMutation } from '@tanstack/react-query';
import type { UseQueryResult, QueryFunctionContext, UseQueryOptions, QueryClient, QueryKey, MutationKey, UseMutationOptions, UseMutationResult, QueryMeta, MutationMeta } from '@tanstack/react-query';
import { trimArrayEnd, isParameterObject, getBaseUrl, addMetaToOptions } from './helpers';
import type { QueryMetaContextValue } from 'react-query-swagger';
import { QueryMetaContext } from 'react-query-swagger';
import { useContext } from 'react';
import * as Client from './AnnouncementClient'
export { Client };
import type { AxiosRequestConfig } from 'axios';

export type CreateAnnouncementAnnouncementQueryParameters = {
  courseId: number ;
  id: string ;
}

export type UpdateAnnouncementAnnouncementQueryParameters = {
  id: number ;
}

export type DeleteAnnouncementAnnouncementQueryParameters = {
  id: number ;
}

export function createAnnouncementUrl(courseId: number, id: string): string {
  let url_ = getBaseUrl() + "/api/courses/{id}/announcements";
if (courseId === undefined || courseId === null)
  throw new Error("The parameter 'courseId' must be defined.");
url_ = url_.replace("{courseId}", encodeURIComponent("" + courseId));
if (id === undefined || id === null)
  throw new Error("The parameter 'id' must be defined.");
url_ = url_.replace("{id}", encodeURIComponent("" + id));
  url_ = url_.replace(/[?&]$/, "");
  return url_;
}

export function createAnnouncementMutationKey(courseId: number, id: string): MutationKey {
  return trimArrayEnd([
      'AnnouncementClient',
      'createAnnouncement',
      courseId as any,
      id as any,
    ]);
}

/**
 * Create announcement
 */
export function useCreateAnnouncementMutation<TContext>(courseId: number, id: string, options?: Omit<UseMutationOptions<Types.PublicationDto, unknown, Types.CreateAnnouncementDto, TContext>, 'mutationKey' | 'mutationFn'>): UseMutationResult<Types.PublicationDto, unknown, Types.CreateAnnouncementDto, TContext> {
  const key = createAnnouncementMutationKey(courseId, id);
  
  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);
  
  return useMutation({
    ...options,
    mutationFn: (dto: Types.CreateAnnouncementDto) => Client.createAnnouncement(courseId, dto, id),
    mutationKey: key,
  });
}
  
type CreateAnnouncement__MutationParameters = CreateAnnouncementAnnouncementQueryParameters & {
  dto: Types.CreateAnnouncementDto;
}

/**
 * Create announcement
 */
export function useCreateAnnouncementMutationWithParameters<TContext>(options?: Omit<UseMutationOptions<Types.PublicationDto, unknown, CreateAnnouncement__MutationParameters, TContext>, 'mutationKey' | 'mutationFn'> & { parameters?: CreateAnnouncementAnnouncementQueryParameters}): UseMutationResult<Types.PublicationDto, unknown, CreateAnnouncement__MutationParameters, TContext> {
  const key = createAnnouncementMutationKey(options?.parameters?.courseId!, options?.parameters?.id!);
  
  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);
  
return useMutation({
  ...options, 
  mutationFn: (data: CreateAnnouncement__MutationParameters) => Client.createAnnouncement(data.courseId ?? options?.parameters?.courseId!, data.dto, data.id ?? options?.parameters?.id!),
  mutationKey: key,
});
}
  
export function updateAnnouncementUrl(id: number): string {
  let url_ = getBaseUrl() + "/api/announcements/{id}";
if (id === undefined || id === null)
  throw new Error("The parameter 'id' must be defined.");
url_ = url_.replace("{id}", encodeURIComponent("" + id));
  url_ = url_.replace(/[?&]$/, "");
  return url_;
}

export function updateAnnouncementMutationKey(id: number): MutationKey {
  return trimArrayEnd([
      'AnnouncementClient',
      'updateAnnouncement',
      id as any,
    ]);
}

/**
 * Update specific announcement
 */
export function useUpdateAnnouncementMutation<TContext>(id: number, options?: Omit<UseMutationOptions<Types.PublicationDto, unknown, Types.PatchAnnouncementDto, TContext>, 'mutationKey' | 'mutationFn'>): UseMutationResult<Types.PublicationDto, unknown, Types.PatchAnnouncementDto, TContext> {
  const key = updateAnnouncementMutationKey(id);
  
  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);
  
  return useMutation({
    ...options,
    mutationFn: (dto: Types.PatchAnnouncementDto) => Client.updateAnnouncement(id, dto),
    mutationKey: key,
  });
}
  
type UpdateAnnouncement__MutationParameters = UpdateAnnouncementAnnouncementQueryParameters & {
  dto: Types.PatchAnnouncementDto;
}

/**
 * Update specific announcement
 */
export function useUpdateAnnouncementMutationWithParameters<TContext>(options?: Omit<UseMutationOptions<Types.PublicationDto, unknown, UpdateAnnouncement__MutationParameters, TContext>, 'mutationKey' | 'mutationFn'> & { parameters?: UpdateAnnouncementAnnouncementQueryParameters}): UseMutationResult<Types.PublicationDto, unknown, UpdateAnnouncement__MutationParameters, TContext> {
  const key = updateAnnouncementMutationKey(options?.parameters?.id!);
  
  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);
  
return useMutation({
  ...options, 
  mutationFn: (data: UpdateAnnouncement__MutationParameters) => Client.updateAnnouncement(data.id ?? options?.parameters?.id!, data.dto),
  mutationKey: key,
});
}
  
export function deleteAnnouncementUrl(id: number): string {
  let url_ = getBaseUrl() + "/api/announcements/{id}";
if (id === undefined || id === null)
  throw new Error("The parameter 'id' must be defined.");
url_ = url_.replace("{id}", encodeURIComponent("" + id));
  url_ = url_.replace(/[?&]$/, "");
  return url_;
}

export function deleteAnnouncementMutationKey(id: number): MutationKey {
  return trimArrayEnd([
      'AnnouncementClient',
      'deleteAnnouncement',
      id as any,
    ]);
}

/**
 * Delete specific announcement
 */
export function useDeleteAnnouncementMutation<TContext>(id: number, options?: Omit<UseMutationOptions<void, unknown, void, TContext>, 'mutationKey' | 'mutationFn'>): UseMutationResult<void, unknown, void, TContext> {
  const key = deleteAnnouncementMutationKey(id);
  
  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);
  
  return useMutation({
    ...options,
    mutationFn: () => Client.deleteAnnouncement(id),
    mutationKey: key,
  });
}
  
type DeleteAnnouncement__MutationParameters = DeleteAnnouncementAnnouncementQueryParameters

/**
 * Delete specific announcement
 */
export function useDeleteAnnouncementMutationWithParameters<TContext>(options?: Omit<UseMutationOptions<void, unknown, DeleteAnnouncement__MutationParameters, TContext>, 'mutationKey' | 'mutationFn'> & { parameters?: DeleteAnnouncementAnnouncementQueryParameters}): UseMutationResult<void, unknown, DeleteAnnouncement__MutationParameters, TContext> {
  const key = deleteAnnouncementMutationKey(options?.parameters?.id!);
  
  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);
  
return useMutation({
  ...options, 
  mutationFn: (data: DeleteAnnouncement__MutationParameters) => Client.deleteAnnouncement(data.id ?? options?.parameters?.id!),
  mutationKey: key,
});
}