//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.20.0.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming
import * as Types from '../api-client.types';
import type { AxiosRequestConfig, AxiosResponse, CancelToken } from 'axios';

import { throwException, isAxiosError } from '../api-client.types';
import { getAxios, getBaseUrl } from './helpers';

/**
 * Gets statistics for specific assignment
 */
export function getAssignmentStatistics(id: number, config?: AxiosRequestConfig | undefined): Promise<Types.AssignmentStatisticDto> {
    let url_ = getBaseUrl() + "/api/assignments/{id}/statistics";
    if (id === undefined || id === null)
      throw new Error("The parameter 'id' must be defined.");
    url_ = url_.replace("{id}", encodeURIComponent("" + id));
      url_ = url_.replace(/[?&]$/, "");

    let options_: AxiosRequestConfig = {
        ..._requestConfigGetAssignmentStatistics,
        ...config,
        method: "GET",
        url: url_,
        headers: {
            ..._requestConfigGetAssignmentStatistics?.headers,
            "Accept": "application/json"
        }
    };

    return getAxios().request(options_).catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
            return _error.response;
        } else {
            throw _error;
        }
    }).then((_response: AxiosResponse) => {
        return processGetAssignmentStatistics(_response);
    });
}

function processGetAssignmentStatistics(response: AxiosResponse): Promise<Types.AssignmentStatisticDto> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === "object") {
        for (let k in response.headers) {
            if (response.headers.hasOwnProperty(k)) {
                _headers[k] = response.headers[k];
            }
        }
    }
    if (status === 400) {
        const _responseText = response.data;
        let result400: any = null;
        let resultData400  = _responseText;
        result400 = Types.initValidationProblemDetails(resultData400);
        return throwException("A server side error occurred.", status, _responseText, _headers, result400);

    } else if (status === 200) {
        const _responseText = response.data;
        let result200: any = null;
        let resultData200  = _responseText;
        result200 = Types.initAssignmentStatisticDto(resultData200);
        return Promise.resolve<Types.AssignmentStatisticDto>(result200);

    } else if (status !== 200 && status !== 204) {
        const _responseText = response.data;
        return throwException("An unexpected server error occurred.", status, _responseText, _headers);
    }
    return Promise.resolve<Types.AssignmentStatisticDto>(null as any);
}

/**
 * Create assignment (check permission)
 */
export function createAssignment(courseId: number, dto: Types.CreateAssignmentDto, config?: AxiosRequestConfig | undefined): Promise<Types.PublicationDto> {
    let url_ = getBaseUrl() + "/api/courses/{courseId}/assignments";
    if (courseId === undefined || courseId === null)
      throw new Error("The parameter 'courseId' must be defined.");
    url_ = url_.replace("{courseId}", encodeURIComponent("" + courseId));
      url_ = url_.replace(/[?&]$/, "");

    const content_ = JSON.stringify(dto);

    let options_: AxiosRequestConfig = {
        ..._requestConfigCreateAssignment,
        ...config,
        data: content_,
        method: "POST",
        url: url_,
        headers: {
            ..._requestConfigCreateAssignment?.headers,
            "Content-Type": "application/json",
            "Accept": "application/json"
        }
    };

    return getAxios().request(options_).catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
            return _error.response;
        } else {
            throw _error;
        }
    }).then((_response: AxiosResponse) => {
        return processCreateAssignment(_response);
    });
}

function processCreateAssignment(response: AxiosResponse): Promise<Types.PublicationDto> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === "object") {
        for (let k in response.headers) {
            if (response.headers.hasOwnProperty(k)) {
                _headers[k] = response.headers[k];
            }
        }
    }
    if (status === 400) {
        const _responseText = response.data;
        let result400: any = null;
        let resultData400  = _responseText;
        result400 = Types.initValidationProblemDetails(resultData400);
        return throwException("A server side error occurred.", status, _responseText, _headers, result400);

    } else if (status === 200) {
        const _responseText = response.data;
        let result200: any = null;
        let resultData200  = _responseText;
        result200 = Types.initPublicationDto(resultData200);
        return Promise.resolve<Types.PublicationDto>(result200);

    } else if (status !== 200 && status !== 204) {
        const _responseText = response.data;
        return throwException("An unexpected server error occurred.", status, _responseText, _headers);
    }
    return Promise.resolve<Types.PublicationDto>(null as any);
}

/**
 * Update specific assignment (check permission)
 */
export function patchAssignment(assignmentId: number, dto: Types.PatchAssignmentDto, config?: AxiosRequestConfig | undefined): Promise<Types.PublicationDto> {
    let url_ = getBaseUrl() + "/api/assignments/{assignmentId}";
    if (assignmentId === undefined || assignmentId === null)
      throw new Error("The parameter 'assignmentId' must be defined.");
    url_ = url_.replace("{assignmentId}", encodeURIComponent("" + assignmentId));
      url_ = url_.replace(/[?&]$/, "");

    const content_ = JSON.stringify(dto);

    let options_: AxiosRequestConfig = {
        ..._requestConfigPatchAssignment,
        ...config,
        data: content_,
        method: "PUT",
        url: url_,
        headers: {
            ..._requestConfigPatchAssignment?.headers,
            "Content-Type": "application/json",
            "Accept": "application/json"
        }
    };

    return getAxios().request(options_).catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
            return _error.response;
        } else {
            throw _error;
        }
    }).then((_response: AxiosResponse) => {
        return processPatchAssignment(_response);
    });
}

function processPatchAssignment(response: AxiosResponse): Promise<Types.PublicationDto> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === "object") {
        for (let k in response.headers) {
            if (response.headers.hasOwnProperty(k)) {
                _headers[k] = response.headers[k];
            }
        }
    }
    if (status === 400) {
        const _responseText = response.data;
        let result400: any = null;
        let resultData400  = _responseText;
        result400 = Types.initValidationProblemDetails(resultData400);
        return throwException("A server side error occurred.", status, _responseText, _headers, result400);

    } else if (status === 200) {
        const _responseText = response.data;
        let result200: any = null;
        let resultData200  = _responseText;
        result200 = Types.initPublicationDto(resultData200);
        return Promise.resolve<Types.PublicationDto>(result200);

    } else if (status !== 200 && status !== 204) {
        const _responseText = response.data;
        return throwException("An unexpected server error occurred.", status, _responseText, _headers);
    }
    return Promise.resolve<Types.PublicationDto>(null as any);
}

/**
 * Delete specific assignment (check permission)
 */
export function deleteAssignment(assignmentId: number, config?: AxiosRequestConfig | undefined): Promise<void> {
    let url_ = getBaseUrl() + "/api/assignments/{assignmentId}";
    if (assignmentId === undefined || assignmentId === null)
      throw new Error("The parameter 'assignmentId' must be defined.");
    url_ = url_.replace("{assignmentId}", encodeURIComponent("" + assignmentId));
      url_ = url_.replace(/[?&]$/, "");

    let options_: AxiosRequestConfig = {
        ..._requestConfigDeleteAssignment,
        ...config,
        method: "DELETE",
        url: url_,
        headers: {
            ..._requestConfigDeleteAssignment?.headers,
        }
    };

    return getAxios().request(options_).catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
            return _error.response;
        } else {
            throw _error;
        }
    }).then((_response: AxiosResponse) => {
        return processDeleteAssignment(_response);
    });
}

function processDeleteAssignment(response: AxiosResponse): Promise<void> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === "object") {
        for (let k in response.headers) {
            if (response.headers.hasOwnProperty(k)) {
                _headers[k] = response.headers[k];
            }
        }
    }
    if (status === 400) {
        const _responseText = response.data;
        let result400: any = null;
        let resultData400  = _responseText;
        result400 = Types.initValidationProblemDetails(resultData400);
        return throwException("A server side error occurred.", status, _responseText, _headers, result400);

    } else if (status === 200) {
        const _responseText = response.data;
        return Promise.resolve<void>(null as any);

    } else if (status !== 200 && status !== 204) {
        const _responseText = response.data;
        return throwException("An unexpected server error occurred.", status, _responseText, _headers);
    }
    return Promise.resolve<void>(null as any);
}
let _requestConfigGetAssignmentStatistics: Partial<AxiosRequestConfig> | null;
export function getGetAssignmentStatisticsRequestConfig() {
  return _requestConfigGetAssignmentStatistics;
}
export function setGetAssignmentStatisticsRequestConfig(value: Partial<AxiosRequestConfig>) {
  _requestConfigGetAssignmentStatistics = value;
}
export function patchGetAssignmentStatisticsRequestConfig(patch: (value: Partial<AxiosRequestConfig>) => Partial<AxiosRequestConfig>) {
  _requestConfigGetAssignmentStatistics = patch(_requestConfigGetAssignmentStatistics ?? {});
}

let _requestConfigCreateAssignment: Partial<AxiosRequestConfig> | null;
export function getCreateAssignmentRequestConfig() {
  return _requestConfigCreateAssignment;
}
export function setCreateAssignmentRequestConfig(value: Partial<AxiosRequestConfig>) {
  _requestConfigCreateAssignment = value;
}
export function patchCreateAssignmentRequestConfig(patch: (value: Partial<AxiosRequestConfig>) => Partial<AxiosRequestConfig>) {
  _requestConfigCreateAssignment = patch(_requestConfigCreateAssignment ?? {});
}

let _requestConfigPatchAssignment: Partial<AxiosRequestConfig> | null;
export function getPatchAssignmentRequestConfig() {
  return _requestConfigPatchAssignment;
}
export function setPatchAssignmentRequestConfig(value: Partial<AxiosRequestConfig>) {
  _requestConfigPatchAssignment = value;
}
export function patchPatchAssignmentRequestConfig(patch: (value: Partial<AxiosRequestConfig>) => Partial<AxiosRequestConfig>) {
  _requestConfigPatchAssignment = patch(_requestConfigPatchAssignment ?? {});
}

let _requestConfigDeleteAssignment: Partial<AxiosRequestConfig> | null;
export function getDeleteAssignmentRequestConfig() {
  return _requestConfigDeleteAssignment;
}
export function setDeleteAssignmentRequestConfig(value: Partial<AxiosRequestConfig>) {
  _requestConfigDeleteAssignment = value;
}
export function patchDeleteAssignmentRequestConfig(patch: (value: Partial<AxiosRequestConfig>) => Partial<AxiosRequestConfig>) {
  _requestConfigDeleteAssignment = patch(_requestConfigDeleteAssignment ?? {});
}