//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.20.0.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming
import * as Types from '../api-client.types';
import { useQuery, useMutation } from '@tanstack/react-query';
import type { UseQueryResult, QueryFunctionContext, UseQueryOptions, QueryClient, QueryKey, MutationKey, UseMutationOptions, UseMutationResult, QueryMeta, MutationMeta } from '@tanstack/react-query';
import { trimArrayEnd, isParameterObject, getBaseUrl, addMetaToOptions } from './helpers';
import type { QueryMetaContextValue } from 'react-query-swagger';
import { QueryMetaContext } from 'react-query-swagger';
import { useContext } from 'react';
import * as Client from './AssignmentClient'
export { Client };
import type { AxiosRequestConfig } from 'axios';

export type GetAssignmentAssignmentQueryParameters = {
  id: number ;
}

export type UpdateAssignmentAssignmentQueryParameters = {
  id: number ;
}

export type DeleteAssignmentAssignmentQueryParameters = {
  id: number ;
}

export type GetAssignmentStatisticsAssignmentQueryParameters = {
  id: number ;
}

export function getAssignmentUrl(id: number): string {
  let url_ = getBaseUrl() + "/api/assignments/{id}";
if (id === undefined || id === null)
  throw new Error("The parameter 'id' must be defined.");
url_ = url_.replace("{id}", encodeURIComponent("" + id));
  url_ = url_.replace(/[?&]$/, "");
  return url_;
}

let getAssignmentDefaultOptions: Omit<UseQueryOptions<Types.AssignmentDto, unknown, Types.AssignmentDto>, 'queryKey'> = {
  queryFn: __getAssignment,
};
export function getGetAssignmentDefaultOptions() {
  return getAssignmentDefaultOptions;
};
export function setGetAssignmentDefaultOptions(options: typeof getAssignmentDefaultOptions) {
  getAssignmentDefaultOptions = options;
}

export function getAssignmentQueryKey(id: number): QueryKey;
export function getAssignmentQueryKey(...params: any[]): QueryKey {
  if (params.length === 1 && isParameterObject(params[0])) {
    const { id,  } = params[0] as GetAssignmentAssignmentQueryParameters;

    return trimArrayEnd([
        'AssignmentClient',
        'getAssignment',
        id as any,
      ]);
  } else {
    return trimArrayEnd([
        'AssignmentClient',
        'getAssignment',
        ...params
      ]);
  }
}
function __getAssignment(context: QueryFunctionContext) {
  return Client.getAssignment(
      context.queryKey[2] as number    );
}

export function useGetAssignmentQuery<TSelectData = Types.AssignmentDto, TError = unknown>(dto: GetAssignmentAssignmentQueryParameters, options?: Omit<UseQueryOptions<Types.AssignmentDto, TError, TSelectData>, 'queryKey'>, axiosConfig?: Partial<AxiosRequestConfig>): UseQueryResult<TSelectData, TError>;
/**
 * Gets full information for specific assignment
 */
export function useGetAssignmentQuery<TSelectData = Types.AssignmentDto, TError = unknown>(id: number, options?: Omit<UseQueryOptions<Types.AssignmentDto, TError, TSelectData>, 'queryKey'>, axiosConfig?: Partial<AxiosRequestConfig>): UseQueryResult<TSelectData, TError>;
export function useGetAssignmentQuery<TSelectData = Types.AssignmentDto, TError = unknown>(...params: any []): UseQueryResult<TSelectData, TError> {
  let options: UseQueryOptions<Types.AssignmentDto, TError, TSelectData> | undefined = undefined;
  let axiosConfig: AxiosRequestConfig |undefined;
  let id: any = undefined;
  
  if (params.length > 0) {
    if (isParameterObject(params[0])) {
      ({ id,  } = params[0] as GetAssignmentAssignmentQueryParameters);
      options = params[1];
      axiosConfig = params[2];
    } else {
      [id, options, axiosConfig] = params;
    }
  }

  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);
  if (axiosConfig) {
    options = options ?? { } as any;
    options!.meta = { ...options!.meta, axiosConfig };
  }

  return useQuery<Types.AssignmentDto, TError, TSelectData>({
    queryFn: __getAssignment,
    queryKey: getAssignmentQueryKey(id),
    ...getAssignmentDefaultOptions as unknown as Omit<UseQueryOptions<Types.AssignmentDto, TError, TSelectData>, 'queryKey'>,
    ...options,
  });
}
/**
 * Gets full information for specific assignment
 */
export function setGetAssignmentData(queryClient: QueryClient, updater: (data: Types.AssignmentDto | undefined) => Types.AssignmentDto, id: number) {
  queryClient.setQueryData(getAssignmentQueryKey(id),
    updater
  );
}

/**
 * Gets full information for specific assignment
 */
export function setGetAssignmentDataByQueryId(queryClient: QueryClient, queryKey: QueryKey, updater: (data: Types.AssignmentDto | undefined) => Types.AssignmentDto) {
  queryClient.setQueryData(queryKey, updater);
}
    
export function updateAssignmentUrl(id: number): string {
  let url_ = getBaseUrl() + "/api/assignments/{id}";
if (id === undefined || id === null)
  throw new Error("The parameter 'id' must be defined.");
url_ = url_.replace("{id}", encodeURIComponent("" + id));
  url_ = url_.replace(/[?&]$/, "");
  return url_;
}

export function updateAssignmentMutationKey(id: number): MutationKey {
  return trimArrayEnd([
      'AssignmentClient',
      'updateAssignment',
      id as any,
    ]);
}

/**
 * Update specific assignment (check permission)
 */
export function useUpdateAssignmentMutation<TContext>(id: number, options?: Omit<UseMutationOptions<void, unknown, Types.CreateAssignmentDto, TContext>, 'mutationKey' | 'mutationFn'>): UseMutationResult<void, unknown, Types.CreateAssignmentDto, TContext> {
  const key = updateAssignmentMutationKey(id);
  
  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);
  
  return useMutation({
    ...options,
    mutationFn: (dto: Types.CreateAssignmentDto) => Client.updateAssignment(id, dto),
    mutationKey: key,
  });
}
  
type UpdateAssignment__MutationParameters = UpdateAssignmentAssignmentQueryParameters & {
  dto: Types.CreateAssignmentDto;
}

/**
 * Update specific assignment (check permission)
 */
export function useUpdateAssignmentMutationWithParameters<TContext>(options?: Omit<UseMutationOptions<void, unknown, UpdateAssignment__MutationParameters, TContext>, 'mutationKey' | 'mutationFn'> & { parameters?: UpdateAssignmentAssignmentQueryParameters}): UseMutationResult<void, unknown, UpdateAssignment__MutationParameters, TContext> {
  const key = updateAssignmentMutationKey(options?.parameters?.id!);
  
  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);
  
return useMutation({
  ...options, 
  mutationFn: (data: UpdateAssignment__MutationParameters) => Client.updateAssignment(data.id ?? options?.parameters?.id!, data.dto),
  mutationKey: key,
});
}
  
export function deleteAssignmentUrl(id: number): string {
  let url_ = getBaseUrl() + "/api/assignments/{id}";
if (id === undefined || id === null)
  throw new Error("The parameter 'id' must be defined.");
url_ = url_.replace("{id}", encodeURIComponent("" + id));
  url_ = url_.replace(/[?&]$/, "");
  return url_;
}

export function deleteAssignmentMutationKey(id: number): MutationKey {
  return trimArrayEnd([
      'AssignmentClient',
      'deleteAssignment',
      id as any,
    ]);
}

/**
 * Delete specific assignment (check permission)
 */
export function useDeleteAssignmentMutation<TContext>(id: number, options?: Omit<UseMutationOptions<void, unknown, void, TContext>, 'mutationKey' | 'mutationFn'>): UseMutationResult<void, unknown, void, TContext> {
  const key = deleteAssignmentMutationKey(id);
  
  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);
  
  return useMutation({
    ...options,
    mutationFn: () => Client.deleteAssignment(id),
    mutationKey: key,
  });
}
  
type DeleteAssignment__MutationParameters = DeleteAssignmentAssignmentQueryParameters

/**
 * Delete specific assignment (check permission)
 */
export function useDeleteAssignmentMutationWithParameters<TContext>(options?: Omit<UseMutationOptions<void, unknown, DeleteAssignment__MutationParameters, TContext>, 'mutationKey' | 'mutationFn'> & { parameters?: DeleteAssignmentAssignmentQueryParameters}): UseMutationResult<void, unknown, DeleteAssignment__MutationParameters, TContext> {
  const key = deleteAssignmentMutationKey(options?.parameters?.id!);
  
  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);
  
return useMutation({
  ...options, 
  mutationFn: (data: DeleteAssignment__MutationParameters) => Client.deleteAssignment(data.id ?? options?.parameters?.id!),
  mutationKey: key,
});
}
  
export function getAssignmentStatisticsUrl(id: number): string {
  let url_ = getBaseUrl() + "/api/assignments/{id}/statistics";
if (id === undefined || id === null)
  throw new Error("The parameter 'id' must be defined.");
url_ = url_.replace("{id}", encodeURIComponent("" + id));
  url_ = url_.replace(/[?&]$/, "");
  return url_;
}

let getAssignmentStatisticsDefaultOptions: Omit<UseQueryOptions<Types.AssignmentStatisticDto, unknown, Types.AssignmentStatisticDto>, 'queryKey'> = {
  queryFn: __getAssignmentStatistics,
};
export function getGetAssignmentStatisticsDefaultOptions() {
  return getAssignmentStatisticsDefaultOptions;
};
export function setGetAssignmentStatisticsDefaultOptions(options: typeof getAssignmentStatisticsDefaultOptions) {
  getAssignmentStatisticsDefaultOptions = options;
}

export function getAssignmentStatisticsQueryKey(id: number): QueryKey;
export function getAssignmentStatisticsQueryKey(...params: any[]): QueryKey {
  if (params.length === 1 && isParameterObject(params[0])) {
    const { id,  } = params[0] as GetAssignmentStatisticsAssignmentQueryParameters;

    return trimArrayEnd([
        'AssignmentClient',
        'getAssignmentStatistics',
        id as any,
      ]);
  } else {
    return trimArrayEnd([
        'AssignmentClient',
        'getAssignmentStatistics',
        ...params
      ]);
  }
}
function __getAssignmentStatistics(context: QueryFunctionContext) {
  return Client.getAssignmentStatistics(
      context.queryKey[2] as number    );
}

export function useGetAssignmentStatisticsQuery<TSelectData = Types.AssignmentStatisticDto, TError = unknown>(dto: GetAssignmentStatisticsAssignmentQueryParameters, options?: Omit<UseQueryOptions<Types.AssignmentStatisticDto, TError, TSelectData>, 'queryKey'>, axiosConfig?: Partial<AxiosRequestConfig>): UseQueryResult<TSelectData, TError>;
/**
 * Gets statistics for specific assignment
 */
export function useGetAssignmentStatisticsQuery<TSelectData = Types.AssignmentStatisticDto, TError = unknown>(id: number, options?: Omit<UseQueryOptions<Types.AssignmentStatisticDto, TError, TSelectData>, 'queryKey'>, axiosConfig?: Partial<AxiosRequestConfig>): UseQueryResult<TSelectData, TError>;
export function useGetAssignmentStatisticsQuery<TSelectData = Types.AssignmentStatisticDto, TError = unknown>(...params: any []): UseQueryResult<TSelectData, TError> {
  let options: UseQueryOptions<Types.AssignmentStatisticDto, TError, TSelectData> | undefined = undefined;
  let axiosConfig: AxiosRequestConfig |undefined;
  let id: any = undefined;
  
  if (params.length > 0) {
    if (isParameterObject(params[0])) {
      ({ id,  } = params[0] as GetAssignmentStatisticsAssignmentQueryParameters);
      options = params[1];
      axiosConfig = params[2];
    } else {
      [id, options, axiosConfig] = params;
    }
  }

  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);
  if (axiosConfig) {
    options = options ?? { } as any;
    options!.meta = { ...options!.meta, axiosConfig };
  }

  return useQuery<Types.AssignmentStatisticDto, TError, TSelectData>({
    queryFn: __getAssignmentStatistics,
    queryKey: getAssignmentStatisticsQueryKey(id),
    ...getAssignmentStatisticsDefaultOptions as unknown as Omit<UseQueryOptions<Types.AssignmentStatisticDto, TError, TSelectData>, 'queryKey'>,
    ...options,
  });
}
/**
 * Gets statistics for specific assignment
 */
export function setGetAssignmentStatisticsData(queryClient: QueryClient, updater: (data: Types.AssignmentStatisticDto | undefined) => Types.AssignmentStatisticDto, id: number) {
  queryClient.setQueryData(getAssignmentStatisticsQueryKey(id),
    updater
  );
}

/**
 * Gets statistics for specific assignment
 */
export function setGetAssignmentStatisticsDataByQueryId(queryClient: QueryClient, queryKey: QueryKey, updater: (data: Types.AssignmentStatisticDto | undefined) => Types.AssignmentStatisticDto) {
  queryClient.setQueryData(queryKey, updater);
}
    
export function createAssignmentUrl(): string {
  let url_ = getBaseUrl() + "/api/assignments";
  url_ = url_.replace(/[?&]$/, "");
  return url_;
}

export function createAssignmentMutationKey(): MutationKey {
  return trimArrayEnd([
      'AssignmentClient',
      'createAssignment',
    ]);
}

/**
 * Create assignment (check permission)
 */
export function useCreateAssignmentMutation<TContext>(options?: Omit<UseMutationOptions<Types.AssignmentDto, unknown, Types.CreateAssignmentDto, TContext>, 'mutationKey' | 'mutationFn'>): UseMutationResult<Types.AssignmentDto, unknown, Types.CreateAssignmentDto, TContext> {
  const key = createAssignmentMutationKey();
  
  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);
  
  return useMutation({
    ...options,
    mutationFn: (dto: Types.CreateAssignmentDto) => Client.createAssignment(dto),
    mutationKey: key,
  });
}