//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.20.0.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming
import * as Types from '../api-client.types';
import { useQuery, useMutation } from '@tanstack/react-query';
import type { UseQueryResult, QueryFunctionContext, UseQueryOptions, QueryClient, QueryKey, MutationKey, UseMutationOptions, UseMutationResult, QueryMeta, MutationMeta } from '@tanstack/react-query';
import { trimArrayEnd, isParameterObject, getBaseUrl, addMetaToOptions } from './helpers';
import type { QueryMetaContextValue } from 'react-query-swagger';
import { QueryMetaContext } from 'react-query-swagger';
import { useContext } from 'react';
import * as Client from './AssignmentClient'
export { Client };
import type { AxiosRequestConfig } from 'axios';

export type GetAssignmentStatisticsAssignmentQueryParameters = {
  id: number ;
}

export type CreateAssignmentAssignmentQueryParameters = {
  courseId: number ;
}

export type PatchAssignmentAssignmentQueryParameters = {
  assignmentId: number ;
}

export type DeleteAssignmentAssignmentQueryParameters = {
  assignmentId: number ;
}

export function getAssignmentStatisticsUrl(id: number): string {
  let url_ = getBaseUrl() + "/api/assignments/{id}/statistics";
if (id === undefined || id === null)
  throw new Error("The parameter 'id' must be defined.");
url_ = url_.replace("{id}", encodeURIComponent("" + id));
  url_ = url_.replace(/[?&]$/, "");
  return url_;
}

let getAssignmentStatisticsDefaultOptions: Omit<UseQueryOptions<Types.AssignmentStatisticDto, unknown, Types.AssignmentStatisticDto>, 'queryKey'> = {
  queryFn: __getAssignmentStatistics,
};
export function getGetAssignmentStatisticsDefaultOptions() {
  return getAssignmentStatisticsDefaultOptions;
};
export function setGetAssignmentStatisticsDefaultOptions(options: typeof getAssignmentStatisticsDefaultOptions) {
  getAssignmentStatisticsDefaultOptions = options;
}

export function getAssignmentStatisticsQueryKey(id: number): QueryKey;
export function getAssignmentStatisticsQueryKey(...params: any[]): QueryKey {
  if (params.length === 1 && isParameterObject(params[0])) {
    const { id,  } = params[0] as GetAssignmentStatisticsAssignmentQueryParameters;

    return trimArrayEnd([
        'AssignmentClient',
        'getAssignmentStatistics',
        id as any,
      ]);
  } else {
    return trimArrayEnd([
        'AssignmentClient',
        'getAssignmentStatistics',
        ...params
      ]);
  }
}
function __getAssignmentStatistics(context: QueryFunctionContext) {
  return Client.getAssignmentStatistics(
      context.queryKey[2] as number    );
}

export function useGetAssignmentStatisticsQuery<TSelectData = Types.AssignmentStatisticDto, TError = unknown>(dto: GetAssignmentStatisticsAssignmentQueryParameters, options?: Omit<UseQueryOptions<Types.AssignmentStatisticDto, TError, TSelectData>, 'queryKey'>, axiosConfig?: Partial<AxiosRequestConfig>): UseQueryResult<TSelectData, TError>;
/**
 * Gets statistics for specific assignment
 */
export function useGetAssignmentStatisticsQuery<TSelectData = Types.AssignmentStatisticDto, TError = unknown>(id: number, options?: Omit<UseQueryOptions<Types.AssignmentStatisticDto, TError, TSelectData>, 'queryKey'>, axiosConfig?: Partial<AxiosRequestConfig>): UseQueryResult<TSelectData, TError>;
export function useGetAssignmentStatisticsQuery<TSelectData = Types.AssignmentStatisticDto, TError = unknown>(...params: any []): UseQueryResult<TSelectData, TError> {
  let options: UseQueryOptions<Types.AssignmentStatisticDto, TError, TSelectData> | undefined = undefined;
  let axiosConfig: AxiosRequestConfig |undefined;
  let id: any = undefined;
  
  if (params.length > 0) {
    if (isParameterObject(params[0])) {
      ({ id,  } = params[0] as GetAssignmentStatisticsAssignmentQueryParameters);
      options = params[1];
      axiosConfig = params[2];
    } else {
      [id, options, axiosConfig] = params;
    }
  }

  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);
  if (axiosConfig) {
    options = options ?? { } as any;
    options!.meta = { ...options!.meta, axiosConfig };
  }

  return useQuery<Types.AssignmentStatisticDto, TError, TSelectData>({
    queryFn: __getAssignmentStatistics,
    queryKey: getAssignmentStatisticsQueryKey(id),
    ...getAssignmentStatisticsDefaultOptions as unknown as Omit<UseQueryOptions<Types.AssignmentStatisticDto, TError, TSelectData>, 'queryKey'>,
    ...options,
  });
}
/**
 * Gets statistics for specific assignment
 */
export function setGetAssignmentStatisticsData(queryClient: QueryClient, updater: (data: Types.AssignmentStatisticDto | undefined) => Types.AssignmentStatisticDto, id: number) {
  queryClient.setQueryData(getAssignmentStatisticsQueryKey(id),
    updater
  );
}

/**
 * Gets statistics for specific assignment
 */
export function setGetAssignmentStatisticsDataByQueryId(queryClient: QueryClient, queryKey: QueryKey, updater: (data: Types.AssignmentStatisticDto | undefined) => Types.AssignmentStatisticDto) {
  queryClient.setQueryData(queryKey, updater);
}
    
export function createAssignmentUrl(courseId: number): string {
  let url_ = getBaseUrl() + "/api/courses/{courseId}/assignments";
if (courseId === undefined || courseId === null)
  throw new Error("The parameter 'courseId' must be defined.");
url_ = url_.replace("{courseId}", encodeURIComponent("" + courseId));
  url_ = url_.replace(/[?&]$/, "");
  return url_;
}

export function createAssignmentMutationKey(courseId: number): MutationKey {
  return trimArrayEnd([
      'AssignmentClient',
      'createAssignment',
      courseId as any,
    ]);
}

/**
 * Create assignment (check permission)
 */
export function useCreateAssignmentMutation<TContext>(courseId: number, options?: Omit<UseMutationOptions<Types.PublicationDto, unknown, Types.CreateAssignmentDto, TContext>, 'mutationKey' | 'mutationFn'>): UseMutationResult<Types.PublicationDto, unknown, Types.CreateAssignmentDto, TContext> {
  const key = createAssignmentMutationKey(courseId);
  
  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);
  
  return useMutation({
    ...options,
    mutationFn: (dto: Types.CreateAssignmentDto) => Client.createAssignment(courseId, dto),
    mutationKey: key,
  });
}
  
type CreateAssignment__MutationParameters = CreateAssignmentAssignmentQueryParameters & {
  dto: Types.CreateAssignmentDto;
}

/**
 * Create assignment (check permission)
 */
export function useCreateAssignmentMutationWithParameters<TContext>(options?: Omit<UseMutationOptions<Types.PublicationDto, unknown, CreateAssignment__MutationParameters, TContext>, 'mutationKey' | 'mutationFn'> & { parameters?: CreateAssignmentAssignmentQueryParameters}): UseMutationResult<Types.PublicationDto, unknown, CreateAssignment__MutationParameters, TContext> {
  const key = createAssignmentMutationKey(options?.parameters?.courseId!);
  
  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);
  
return useMutation({
  ...options, 
  mutationFn: (data: CreateAssignment__MutationParameters) => Client.createAssignment(data.courseId ?? options?.parameters?.courseId!, data.dto),
  mutationKey: key,
});
}
  
export function patchAssignmentUrl(assignmentId: number): string {
  let url_ = getBaseUrl() + "/api/assignments/{assignmentId}";
if (assignmentId === undefined || assignmentId === null)
  throw new Error("The parameter 'assignmentId' must be defined.");
url_ = url_.replace("{assignmentId}", encodeURIComponent("" + assignmentId));
  url_ = url_.replace(/[?&]$/, "");
  return url_;
}

export function patchAssignmentMutationKey(assignmentId: number): MutationKey {
  return trimArrayEnd([
      'AssignmentClient',
      'patchAssignment',
      assignmentId as any,
    ]);
}

/**
 * Update specific assignment (check permission)
 */
export function usePatchAssignmentMutation<TContext>(assignmentId: number, options?: Omit<UseMutationOptions<Types.PublicationDto, unknown, Types.PatchAssignmentDto, TContext>, 'mutationKey' | 'mutationFn'>): UseMutationResult<Types.PublicationDto, unknown, Types.PatchAssignmentDto, TContext> {
  const key = patchAssignmentMutationKey(assignmentId);
  
  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);
  
  return useMutation({
    ...options,
    mutationFn: (dto: Types.PatchAssignmentDto) => Client.patchAssignment(assignmentId, dto),
    mutationKey: key,
  });
}
  
type PatchAssignment__MutationParameters = PatchAssignmentAssignmentQueryParameters & {
  dto: Types.PatchAssignmentDto;
}

/**
 * Update specific assignment (check permission)
 */
export function usePatchAssignmentMutationWithParameters<TContext>(options?: Omit<UseMutationOptions<Types.PublicationDto, unknown, PatchAssignment__MutationParameters, TContext>, 'mutationKey' | 'mutationFn'> & { parameters?: PatchAssignmentAssignmentQueryParameters}): UseMutationResult<Types.PublicationDto, unknown, PatchAssignment__MutationParameters, TContext> {
  const key = patchAssignmentMutationKey(options?.parameters?.assignmentId!);
  
  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);
  
return useMutation({
  ...options, 
  mutationFn: (data: PatchAssignment__MutationParameters) => Client.patchAssignment(data.assignmentId ?? options?.parameters?.assignmentId!, data.dto),
  mutationKey: key,
});
}
  
export function deleteAssignmentUrl(assignmentId: number): string {
  let url_ = getBaseUrl() + "/api/assignments/{assignmentId}";
if (assignmentId === undefined || assignmentId === null)
  throw new Error("The parameter 'assignmentId' must be defined.");
url_ = url_.replace("{assignmentId}", encodeURIComponent("" + assignmentId));
  url_ = url_.replace(/[?&]$/, "");
  return url_;
}

export function deleteAssignmentMutationKey(assignmentId: number): MutationKey {
  return trimArrayEnd([
      'AssignmentClient',
      'deleteAssignment',
      assignmentId as any,
    ]);
}

/**
 * Delete specific assignment (check permission)
 */
export function useDeleteAssignmentMutation<TContext>(assignmentId: number, options?: Omit<UseMutationOptions<void, unknown, void, TContext>, 'mutationKey' | 'mutationFn'>): UseMutationResult<void, unknown, void, TContext> {
  const key = deleteAssignmentMutationKey(assignmentId);
  
  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);
  
  return useMutation({
    ...options,
    mutationFn: () => Client.deleteAssignment(assignmentId),
    mutationKey: key,
  });
}
  
type DeleteAssignment__MutationParameters = DeleteAssignmentAssignmentQueryParameters

/**
 * Delete specific assignment (check permission)
 */
export function useDeleteAssignmentMutationWithParameters<TContext>(options?: Omit<UseMutationOptions<void, unknown, DeleteAssignment__MutationParameters, TContext>, 'mutationKey' | 'mutationFn'> & { parameters?: DeleteAssignmentAssignmentQueryParameters}): UseMutationResult<void, unknown, DeleteAssignment__MutationParameters, TContext> {
  const key = deleteAssignmentMutationKey(options?.parameters?.assignmentId!);
  
  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);
  
return useMutation({
  ...options, 
  mutationFn: (data: DeleteAssignment__MutationParameters) => Client.deleteAssignment(data.assignmentId ?? options?.parameters?.assignmentId!),
  mutationKey: key,
});
}