//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.20.0.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming
import * as Types from '../api-client.types';
import type { AxiosRequestConfig, AxiosResponse, CancelToken } from 'axios';

import { throwException, isAxiosError } from '../api-client.types';
import { getAxios, getBaseUrl } from './helpers';

/**
 * Retrieves all Comments of the specified Assignment.
 */
export function getAssignmentComments(assignmentId: number, config?: AxiosRequestConfig | undefined): Promise<Types.PagedResultOfCommentDto> {
    let url_ = getBaseUrl() + "/api/assignments/{assignmentId}/comments";
    if (assignmentId === undefined || assignmentId === null)
      throw new Error("The parameter 'assignmentId' must be defined.");
    url_ = url_.replace("{assignmentId}", encodeURIComponent("" + assignmentId));
      url_ = url_.replace(/[?&]$/, "");

    let options_: AxiosRequestConfig = {
        ..._requestConfigGetAssignmentComments,
        ...config,
        method: "GET",
        url: url_,
        headers: {
            ..._requestConfigGetAssignmentComments?.headers,
            "Accept": "application/json"
        }
    };

    return getAxios().request(options_).catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
            return _error.response;
        } else {
            throw _error;
        }
    }).then((_response: AxiosResponse) => {
        return processGetAssignmentComments(_response);
    });
}

function processGetAssignmentComments(response: AxiosResponse): Promise<Types.PagedResultOfCommentDto> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === "object") {
        for (let k in response.headers) {
            if (response.headers.hasOwnProperty(k)) {
                _headers[k] = response.headers[k];
            }
        }
    }
    if (status === 400) {
        const _responseText = response.data;
        let result400: any = null;
        let resultData400  = _responseText;
        result400 = Types.initValidationProblemDetails(resultData400);
        return throwException("A server side error occurred.", status, _responseText, _headers, result400);

    } else if (status === 200) {
        const _responseText = response.data;
        let result200: any = null;
        let resultData200  = _responseText;
        result200 = Types.initPagedResultOfCommentDto(resultData200);
        return Promise.resolve<Types.PagedResultOfCommentDto>(result200);

    } else if (status !== 200 && status !== 204) {
        const _responseText = response.data;
        return throwException("An unexpected server error occurred.", status, _responseText, _headers);
    }
    return Promise.resolve<Types.PagedResultOfCommentDto>(null as any);
}

/**
 * Adds a Comment to the specified Assignment.
 */
export function addCommentToAssignment(assignmentId: number, createCommentDto: Types.CreateCommentDto, config?: AxiosRequestConfig | undefined): Promise<Types.CommentDto> {
    let url_ = getBaseUrl() + "/api/assignments/{assignmentId}/comments";
    if (assignmentId === undefined || assignmentId === null)
      throw new Error("The parameter 'assignmentId' must be defined.");
    url_ = url_.replace("{assignmentId}", encodeURIComponent("" + assignmentId));
      url_ = url_.replace(/[?&]$/, "");

    const content_ = Types.serializeCreateCommentDto(createCommentDto);

    let options_: AxiosRequestConfig = {
        ..._requestConfigAddCommentToAssignment,
        ...config,
        data: content_,
        method: "POST",
        url: url_,
        headers: {
            ..._requestConfigAddCommentToAssignment?.headers,
            "Content-Type": "application/json",
            "Accept": "application/json"
        }
    };

    return getAxios().request(options_).catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
            return _error.response;
        } else {
            throw _error;
        }
    }).then((_response: AxiosResponse) => {
        return processAddCommentToAssignment(_response);
    });
}

function processAddCommentToAssignment(response: AxiosResponse): Promise<Types.CommentDto> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === "object") {
        for (let k in response.headers) {
            if (response.headers.hasOwnProperty(k)) {
                _headers[k] = response.headers[k];
            }
        }
    }
    if (status === 400) {
        const _responseText = response.data;
        let result400: any = null;
        let resultData400  = _responseText;
        result400 = Types.initValidationProblemDetails(resultData400);
        return throwException("A server side error occurred.", status, _responseText, _headers, result400);

    } else if (status === 200) {
        const _responseText = response.data;
        let result200: any = null;
        let resultData200  = _responseText;
        result200 = Types.initCommentDto(resultData200);
        return Promise.resolve<Types.CommentDto>(result200);

    } else if (status !== 200 && status !== 204) {
        const _responseText = response.data;
        return throwException("An unexpected server error occurred.", status, _responseText, _headers);
    }
    return Promise.resolve<Types.CommentDto>(null as any);
}

/**
 * Retrieves all Comments of the specified Publication.
 */
export function getPublicationComments(publicationId: number, config?: AxiosRequestConfig | undefined): Promise<Types.PagedResultOfCommentDto> {
    let url_ = getBaseUrl() + "/api/publication/{publicationId}/comments";
    if (publicationId === undefined || publicationId === null)
      throw new Error("The parameter 'publicationId' must be defined.");
    url_ = url_.replace("{publicationId}", encodeURIComponent("" + publicationId));
      url_ = url_.replace(/[?&]$/, "");

    let options_: AxiosRequestConfig = {
        ..._requestConfigGetPublicationComments,
        ...config,
        method: "GET",
        url: url_,
        headers: {
            ..._requestConfigGetPublicationComments?.headers,
            "Accept": "application/json"
        }
    };

    return getAxios().request(options_).catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
            return _error.response;
        } else {
            throw _error;
        }
    }).then((_response: AxiosResponse) => {
        return processGetPublicationComments(_response);
    });
}

function processGetPublicationComments(response: AxiosResponse): Promise<Types.PagedResultOfCommentDto> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === "object") {
        for (let k in response.headers) {
            if (response.headers.hasOwnProperty(k)) {
                _headers[k] = response.headers[k];
            }
        }
    }
    if (status === 400) {
        const _responseText = response.data;
        let result400: any = null;
        let resultData400  = _responseText;
        result400 = Types.initValidationProblemDetails(resultData400);
        return throwException("A server side error occurred.", status, _responseText, _headers, result400);

    } else if (status === 200) {
        const _responseText = response.data;
        let result200: any = null;
        let resultData200  = _responseText;
        result200 = Types.initPagedResultOfCommentDto(resultData200);
        return Promise.resolve<Types.PagedResultOfCommentDto>(result200);

    } else if (status !== 200 && status !== 204) {
        const _responseText = response.data;
        return throwException("An unexpected server error occurred.", status, _responseText, _headers);
    }
    return Promise.resolve<Types.PagedResultOfCommentDto>(null as any);
}

/**
 * Adds a Comment to the specified Publication.
 */
export function addCommentToPublication(publicationId: number, createCommentDto: Types.CreateCommentDto, config?: AxiosRequestConfig | undefined): Promise<Types.CommentDto> {
    let url_ = getBaseUrl() + "/api/publication/{publicationId}/comments";
    if (publicationId === undefined || publicationId === null)
      throw new Error("The parameter 'publicationId' must be defined.");
    url_ = url_.replace("{publicationId}", encodeURIComponent("" + publicationId));
      url_ = url_.replace(/[?&]$/, "");

    const content_ = Types.serializeCreateCommentDto(createCommentDto);

    let options_: AxiosRequestConfig = {
        ..._requestConfigAddCommentToPublication,
        ...config,
        data: content_,
        method: "POST",
        url: url_,
        headers: {
            ..._requestConfigAddCommentToPublication?.headers,
            "Content-Type": "application/json",
            "Accept": "application/json"
        }
    };

    return getAxios().request(options_).catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
            return _error.response;
        } else {
            throw _error;
        }
    }).then((_response: AxiosResponse) => {
        return processAddCommentToPublication(_response);
    });
}

function processAddCommentToPublication(response: AxiosResponse): Promise<Types.CommentDto> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === "object") {
        for (let k in response.headers) {
            if (response.headers.hasOwnProperty(k)) {
                _headers[k] = response.headers[k];
            }
        }
    }
    if (status === 400) {
        const _responseText = response.data;
        let result400: any = null;
        let resultData400  = _responseText;
        result400 = Types.initValidationProblemDetails(resultData400);
        return throwException("A server side error occurred.", status, _responseText, _headers, result400);

    } else if (status === 200) {
        const _responseText = response.data;
        let result200: any = null;
        let resultData200  = _responseText;
        result200 = Types.initCommentDto(resultData200);
        return Promise.resolve<Types.CommentDto>(result200);

    } else if (status !== 200 && status !== 204) {
        const _responseText = response.data;
        return throwException("An unexpected server error occurred.", status, _responseText, _headers);
    }
    return Promise.resolve<Types.CommentDto>(null as any);
}

/**
 * Edits a Comment. Only the author of the comment or an admin can edit a comment.
 */
export function editComment(commentId: number, patchCommentDto: Types.PatchCommentDto, config?: AxiosRequestConfig | undefined): Promise<void> {
    let url_ = getBaseUrl() + "/api/comments/{commentId}";
    if (commentId === undefined || commentId === null)
      throw new Error("The parameter 'commentId' must be defined.");
    url_ = url_.replace("{commentId}", encodeURIComponent("" + commentId));
      url_ = url_.replace(/[?&]$/, "");

    const content_ = Types.serializePatchCommentDto(patchCommentDto);

    let options_: AxiosRequestConfig = {
        ..._requestConfigEditComment,
        ...config,
        data: content_,
        method: "PATCH",
        url: url_,
        headers: {
            ..._requestConfigEditComment?.headers,
            "Content-Type": "application/json",
        }
    };

    return getAxios().request(options_).catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
            return _error.response;
        } else {
            throw _error;
        }
    }).then((_response: AxiosResponse) => {
        return processEditComment(_response);
    });
}

function processEditComment(response: AxiosResponse): Promise<void> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === "object") {
        for (let k in response.headers) {
            if (response.headers.hasOwnProperty(k)) {
                _headers[k] = response.headers[k];
            }
        }
    }
    if (status === 400) {
        const _responseText = response.data;
        let result400: any = null;
        let resultData400  = _responseText;
        result400 = Types.initValidationProblemDetails(resultData400);
        return throwException("A server side error occurred.", status, _responseText, _headers, result400);

    } else if (status === 200) {
        const _responseText = response.data;
        return Promise.resolve<void>(null as any);

    } else if (status !== 200 && status !== 204) {
        const _responseText = response.data;
        return throwException("An unexpected server error occurred.", status, _responseText, _headers);
    }
    return Promise.resolve<void>(null as any);
}

/**
 * Deletes a Comment.
Only the author of the comment or an admin can delete a comment.
 */
export function deleteComment(commentId: number, config?: AxiosRequestConfig | undefined): Promise<void> {
    let url_ = getBaseUrl() + "/api/comments/{commentId}";
    if (commentId === undefined || commentId === null)
      throw new Error("The parameter 'commentId' must be defined.");
    url_ = url_.replace("{commentId}", encodeURIComponent("" + commentId));
      url_ = url_.replace(/[?&]$/, "");

    let options_: AxiosRequestConfig = {
        ..._requestConfigDeleteComment,
        ...config,
        method: "DELETE",
        url: url_,
        headers: {
            ..._requestConfigDeleteComment?.headers,
        }
    };

    return getAxios().request(options_).catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
            return _error.response;
        } else {
            throw _error;
        }
    }).then((_response: AxiosResponse) => {
        return processDeleteComment(_response);
    });
}

function processDeleteComment(response: AxiosResponse): Promise<void> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === "object") {
        for (let k in response.headers) {
            if (response.headers.hasOwnProperty(k)) {
                _headers[k] = response.headers[k];
            }
        }
    }
    if (status === 400) {
        const _responseText = response.data;
        let result400: any = null;
        let resultData400  = _responseText;
        result400 = Types.initValidationProblemDetails(resultData400);
        return throwException("A server side error occurred.", status, _responseText, _headers, result400);

    } else if (status === 200) {
        const _responseText = response.data;
        return Promise.resolve<void>(null as any);

    } else if (status !== 200 && status !== 204) {
        const _responseText = response.data;
        return throwException("An unexpected server error occurred.", status, _responseText, _headers);
    }
    return Promise.resolve<void>(null as any);
}
let _requestConfigGetAssignmentComments: Partial<AxiosRequestConfig> | null;
export function getGetAssignmentCommentsRequestConfig() {
  return _requestConfigGetAssignmentComments;
}
export function setGetAssignmentCommentsRequestConfig(value: Partial<AxiosRequestConfig>) {
  _requestConfigGetAssignmentComments = value;
}
export function patchGetAssignmentCommentsRequestConfig(patch: (value: Partial<AxiosRequestConfig>) => Partial<AxiosRequestConfig>) {
  _requestConfigGetAssignmentComments = patch(_requestConfigGetAssignmentComments ?? {});
}

let _requestConfigAddCommentToAssignment: Partial<AxiosRequestConfig> | null;
export function getAddCommentToAssignmentRequestConfig() {
  return _requestConfigAddCommentToAssignment;
}
export function setAddCommentToAssignmentRequestConfig(value: Partial<AxiosRequestConfig>) {
  _requestConfigAddCommentToAssignment = value;
}
export function patchAddCommentToAssignmentRequestConfig(patch: (value: Partial<AxiosRequestConfig>) => Partial<AxiosRequestConfig>) {
  _requestConfigAddCommentToAssignment = patch(_requestConfigAddCommentToAssignment ?? {});
}

let _requestConfigGetPublicationComments: Partial<AxiosRequestConfig> | null;
export function getGetPublicationCommentsRequestConfig() {
  return _requestConfigGetPublicationComments;
}
export function setGetPublicationCommentsRequestConfig(value: Partial<AxiosRequestConfig>) {
  _requestConfigGetPublicationComments = value;
}
export function patchGetPublicationCommentsRequestConfig(patch: (value: Partial<AxiosRequestConfig>) => Partial<AxiosRequestConfig>) {
  _requestConfigGetPublicationComments = patch(_requestConfigGetPublicationComments ?? {});
}

let _requestConfigAddCommentToPublication: Partial<AxiosRequestConfig> | null;
export function getAddCommentToPublicationRequestConfig() {
  return _requestConfigAddCommentToPublication;
}
export function setAddCommentToPublicationRequestConfig(value: Partial<AxiosRequestConfig>) {
  _requestConfigAddCommentToPublication = value;
}
export function patchAddCommentToPublicationRequestConfig(patch: (value: Partial<AxiosRequestConfig>) => Partial<AxiosRequestConfig>) {
  _requestConfigAddCommentToPublication = patch(_requestConfigAddCommentToPublication ?? {});
}

let _requestConfigEditComment: Partial<AxiosRequestConfig> | null;
export function getEditCommentRequestConfig() {
  return _requestConfigEditComment;
}
export function setEditCommentRequestConfig(value: Partial<AxiosRequestConfig>) {
  _requestConfigEditComment = value;
}
export function patchEditCommentRequestConfig(patch: (value: Partial<AxiosRequestConfig>) => Partial<AxiosRequestConfig>) {
  _requestConfigEditComment = patch(_requestConfigEditComment ?? {});
}

let _requestConfigDeleteComment: Partial<AxiosRequestConfig> | null;
export function getDeleteCommentRequestConfig() {
  return _requestConfigDeleteComment;
}
export function setDeleteCommentRequestConfig(value: Partial<AxiosRequestConfig>) {
  _requestConfigDeleteComment = value;
}
export function patchDeleteCommentRequestConfig(patch: (value: Partial<AxiosRequestConfig>) => Partial<AxiosRequestConfig>) {
  _requestConfigDeleteComment = patch(_requestConfigDeleteComment ?? {});
}