//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.20.0.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming
import * as Types from '../api-client.types';
import { useQuery, useMutation } from '@tanstack/react-query';
import type { UseQueryResult, QueryFunctionContext, UseQueryOptions, QueryClient, QueryKey, MutationKey, UseMutationOptions, UseMutationResult, QueryMeta, MutationMeta } from '@tanstack/react-query';
import { trimArrayEnd, isParameterObject, getBaseUrl, addMetaToOptions } from './helpers';
import type { QueryMetaContextValue } from 'react-query-swagger';
import { QueryMetaContext } from 'react-query-swagger';
import { useContext } from 'react';
import * as Client from './CriteriaClient'
export { Client };
import type { AxiosRequestConfig } from 'axios';

export type PatchCriteriaCriteriaQueryParameters = {
  criteriaId: number ;
}

export type DeleteCriteriaCriteriaQueryParameters = {
  criteriaId: number ;
}

export function patchCriteriaUrl(criteriaId: number): string {
  let url_ = getBaseUrl() + "/api/criteria/{criteriaId}";
if (criteriaId === undefined || criteriaId === null)
  throw new Error("The parameter 'criteriaId' must be defined.");
url_ = url_.replace("{criteriaId}", encodeURIComponent("" + criteriaId));
  url_ = url_.replace(/[?&]$/, "");
  return url_;
}

export function patchCriteriaMutationKey(criteriaId: number): MutationKey {
  return trimArrayEnd([
      'CriteriaClient',
      'patchCriteria',
      criteriaId as any,
    ]);
}

/**
 * Update specific criteria
 */
export function usePatchCriteriaMutation<TContext>(criteriaId: number, options?: Omit<UseMutationOptions<Types.CriteriaDto, unknown, Types.PatchCriteriaDto, TContext>, 'mutationKey' | 'mutationFn'>): UseMutationResult<Types.CriteriaDto, unknown, Types.PatchCriteriaDto, TContext> {
  const key = patchCriteriaMutationKey(criteriaId);
  
  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);
  
  return useMutation({
    ...options,
    mutationFn: (patchCriteriaDto: Types.PatchCriteriaDto) => Client.patchCriteria(criteriaId, patchCriteriaDto),
    mutationKey: key,
  });
}
  
type PatchCriteria__MutationParameters = PatchCriteriaCriteriaQueryParameters & {
  patchCriteriaDto: Types.PatchCriteriaDto;
}

/**
 * Update specific criteria
 */
export function usePatchCriteriaMutationWithParameters<TContext>(options?: Omit<UseMutationOptions<Types.CriteriaDto, unknown, PatchCriteria__MutationParameters, TContext>, 'mutationKey' | 'mutationFn'> & { parameters?: PatchCriteriaCriteriaQueryParameters}): UseMutationResult<Types.CriteriaDto, unknown, PatchCriteria__MutationParameters, TContext> {
  const key = patchCriteriaMutationKey(options?.parameters?.criteriaId!);
  
  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);
  
return useMutation({
  ...options, 
  mutationFn: (data: PatchCriteria__MutationParameters) => Client.patchCriteria(data.criteriaId ?? options?.parameters?.criteriaId!, data.patchCriteriaDto),
  mutationKey: key,
});
}
  
export function deleteCriteriaUrl(criteriaId: number): string {
  let url_ = getBaseUrl() + "/api/criteria/{criteriaId}";
if (criteriaId === undefined || criteriaId === null)
  throw new Error("The parameter 'criteriaId' must be defined.");
url_ = url_.replace("{criteriaId}", encodeURIComponent("" + criteriaId));
  url_ = url_.replace(/[?&]$/, "");
  return url_;
}

export function deleteCriteriaMutationKey(criteriaId: number): MutationKey {
  return trimArrayEnd([
      'CriteriaClient',
      'deleteCriteria',
      criteriaId as any,
    ]);
}

/**
 * Delete specific criteria
 */
export function useDeleteCriteriaMutation<TContext>(criteriaId: number, options?: Omit<UseMutationOptions<void, unknown, void, TContext>, 'mutationKey' | 'mutationFn'>): UseMutationResult<void, unknown, void, TContext> {
  const key = deleteCriteriaMutationKey(criteriaId);
  
  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);
  
  return useMutation({
    ...options,
    mutationFn: () => Client.deleteCriteria(criteriaId),
    mutationKey: key,
  });
}
  
type DeleteCriteria__MutationParameters = DeleteCriteriaCriteriaQueryParameters

/**
 * Delete specific criteria
 */
export function useDeleteCriteriaMutationWithParameters<TContext>(options?: Omit<UseMutationOptions<void, unknown, DeleteCriteria__MutationParameters, TContext>, 'mutationKey' | 'mutationFn'> & { parameters?: DeleteCriteriaCriteriaQueryParameters}): UseMutationResult<void, unknown, DeleteCriteria__MutationParameters, TContext> {
  const key = deleteCriteriaMutationKey(options?.parameters?.criteriaId!);
  
  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);
  
return useMutation({
  ...options, 
  mutationFn: (data: DeleteCriteria__MutationParameters) => Client.deleteCriteria(data.criteriaId ?? options?.parameters?.criteriaId!),
  mutationKey: key,
});
}