//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.20.0.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming
import * as Types from '../api-client.types';
import { useQuery, useMutation } from '@tanstack/react-query';
import type { UseQueryResult, QueryFunctionContext, UseQueryOptions, QueryClient, QueryKey, MutationKey, UseMutationOptions, UseMutationResult, QueryMeta, MutationMeta } from '@tanstack/react-query';
import { trimArrayEnd, isParameterObject, getBaseUrl, addMetaToOptions } from './helpers';
import type { QueryMetaContextValue } from 'react-query-swagger';
import { QueryMetaContext } from 'react-query-swagger';
import { useContext } from 'react';
import * as Client from './FilesClient'
export { Client };
import type { AxiosRequestConfig } from 'axios';

export type UploadFileFilesMutationParameters = {
  file?: Types.FileParameter | null | undefined ;
}

export type DownloadFileFilesQueryParameters = {
  fileId: string ;
}

export type DeleteFilesQueryParameters = {
  fileId: string ;
}

export function uploadFileUrl(): string {
  let url_ = getBaseUrl() + "/api/files";
  url_ = url_.replace(/[?&]$/, "");
  return url_;
}

export function uploadFileMutationKey(): MutationKey {
  return trimArrayEnd([
      'FilesClient',
      'uploadFile',
    ]);
}

/**
 * Uploads a file and returns its metadata. The file is expected to be sent as form data with the key "file".
 * @param file (optional) 
 */
export function useUploadFileMutation<TContext>(options?: Omit<UseMutationOptions<Types.FileInfoDto, unknown, UploadFileFilesMutationParameters, TContext>, 'mutationKey' | 'mutationFn'>): UseMutationResult<Types.FileInfoDto, unknown, UploadFileFilesMutationParameters, TContext> {
  const key = uploadFileMutationKey();
  
  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);
  
  return useMutation({
    ...options,
    mutationFn: (uploadFileFilesMutationParameters: UploadFileFilesMutationParameters) => Client.uploadFile(uploadFileFilesMutationParameters.file),
    mutationKey: key,
  });
}
  
export function downloadFileUrl(fileId: string): string {
  let url_ = getBaseUrl() + "/api/files/{fileId}";
if (fileId === undefined || fileId === null)
  throw new Error("The parameter 'fileId' must be defined.");
url_ = url_.replace("{fileId}", encodeURIComponent("" + fileId));
  url_ = url_.replace(/[?&]$/, "");
  return url_;
}

let downloadFileDefaultOptions: Omit<UseQueryOptions<Types.FileResponse, unknown, Types.FileResponse>, 'queryKey'> = {
  queryFn: __downloadFile,
};
export function getDownloadFileDefaultOptions() {
  return downloadFileDefaultOptions;
};
export function setDownloadFileDefaultOptions(options: typeof downloadFileDefaultOptions) {
  downloadFileDefaultOptions = options;
}

export function downloadFileQueryKey(fileId: string): QueryKey;
export function downloadFileQueryKey(...params: any[]): QueryKey {
  if (params.length === 1 && isParameterObject(params[0])) {
    const { fileId,  } = params[0] as DownloadFileFilesQueryParameters;

    return trimArrayEnd([
        'FilesClient',
        'downloadFile',
        fileId as any,
      ]);
  } else {
    return trimArrayEnd([
        'FilesClient',
        'downloadFile',
        ...params
      ]);
  }
}
function __downloadFile(context: QueryFunctionContext) {
  return Client.downloadFile(
      context.queryKey[2] as string    );
}

export function useDownloadFileQuery<TSelectData = Types.FileResponse, TError = unknown>(dto: DownloadFileFilesQueryParameters, options?: Omit<UseQueryOptions<Types.FileResponse, TError, TSelectData>, 'queryKey'>, axiosConfig?: Partial<AxiosRequestConfig>): UseQueryResult<TSelectData, TError>;
/**
 * Downloads a file by its ID. The file is returned as a stream with the appropriate content type and file name.
 */
export function useDownloadFileQuery<TSelectData = Types.FileResponse, TError = unknown>(fileId: string, options?: Omit<UseQueryOptions<Types.FileResponse, TError, TSelectData>, 'queryKey'>, axiosConfig?: Partial<AxiosRequestConfig>): UseQueryResult<TSelectData, TError>;
export function useDownloadFileQuery<TSelectData = Types.FileResponse, TError = unknown>(...params: any []): UseQueryResult<TSelectData, TError> {
  let options: UseQueryOptions<Types.FileResponse, TError, TSelectData> | undefined = undefined;
  let axiosConfig: AxiosRequestConfig |undefined;
  let fileId: any = undefined;
  
  if (params.length > 0) {
    if (isParameterObject(params[0])) {
      ({ fileId,  } = params[0] as DownloadFileFilesQueryParameters);
      options = params[1];
      axiosConfig = params[2];
    } else {
      [fileId, options, axiosConfig] = params;
    }
  }

  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);
  if (axiosConfig) {
    options = options ?? { } as any;
    options!.meta = { ...options!.meta, axiosConfig };
  }

  return useQuery<Types.FileResponse, TError, TSelectData>({
    queryFn: __downloadFile,
    queryKey: downloadFileQueryKey(fileId),
    ...downloadFileDefaultOptions as unknown as Omit<UseQueryOptions<Types.FileResponse, TError, TSelectData>, 'queryKey'>,
    ...options,
  });
}
/**
 * Downloads a file by its ID. The file is returned as a stream with the appropriate content type and file name.
 */
export function setDownloadFileData(queryClient: QueryClient, updater: (data: Types.FileResponse | undefined) => Types.FileResponse, fileId: string) {
  queryClient.setQueryData(downloadFileQueryKey(fileId),
    updater
  );
}

/**
 * Downloads a file by its ID. The file is returned as a stream with the appropriate content type and file name.
 */
export function setDownloadFileDataByQueryId(queryClient: QueryClient, queryKey: QueryKey, updater: (data: Types.FileResponse | undefined) => Types.FileResponse) {
  queryClient.setQueryData(queryKey, updater);
}
    
export function deleteUrl(fileId: string): string {
  let url_ = getBaseUrl() + "/api/files/{fileId}";
if (fileId === undefined || fileId === null)
  throw new Error("The parameter 'fileId' must be defined.");
url_ = url_.replace("{fileId}", encodeURIComponent("" + fileId));
  url_ = url_.replace(/[?&]$/, "");
  return url_;
}

export function deleteMutationKey(fileId: string): MutationKey {
  return trimArrayEnd([
      'FilesClient',
      'delete',
      fileId as any,
    ]);
}

/**
 * Deletes a file by its ID. This operation removes the file from both the disk and the database.
 */
export function useDeleteMutation<TContext>(fileId: string, options?: Omit<UseMutationOptions<void, unknown, void, TContext>, 'mutationKey' | 'mutationFn'>): UseMutationResult<void, unknown, void, TContext> {
  const key = deleteMutationKey(fileId);
  
  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);
  
  return useMutation({
    ...options,
    mutationFn: () => Client.delete_(fileId),
    mutationKey: key,
  });
}
  
type Delete__MutationParameters = DeleteFilesQueryParameters

/**
 * Deletes a file by its ID. This operation removes the file from both the disk and the database.
 */
export function useDeleteMutationWithParameters<TContext>(options?: Omit<UseMutationOptions<void, unknown, Delete__MutationParameters, TContext>, 'mutationKey' | 'mutationFn'> & { parameters?: DeleteFilesQueryParameters}): UseMutationResult<void, unknown, Delete__MutationParameters, TContext> {
  const key = deleteMutationKey(options?.parameters?.fileId!);
  
  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);
  
return useMutation({
  ...options, 
  mutationFn: (data: Delete__MutationParameters) => Client.delete_(data.fileId ?? options?.parameters?.fileId!),
  mutationKey: key,
});
}