//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.20.0.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming
import * as Types from '../api-client.types';
import type { AxiosRequestConfig, AxiosResponse, CancelToken } from 'axios';

import { throwException, isAxiosError } from '../api-client.types';
import { getAxios, getBaseUrl } from './helpers';

/**
 * Invite user to join your team
 */
export function sendInvitation(teamId: number, studentId: string, config?: AxiosRequestConfig | undefined): Promise<void> {
    let url_ = getBaseUrl() + "/api/teams/{teamId}/invite";
    if (teamId === undefined || teamId === null)
      throw new Error("The parameter 'teamId' must be defined.");
    url_ = url_.replace("{teamId}", encodeURIComponent("" + teamId));
      url_ = url_.replace(/[?&]$/, "");

    const content_ = JSON.stringify(studentId);

    let options_: AxiosRequestConfig = {
        ..._requestConfigSendInvitation,
        ...config,
        data: content_,
        method: "POST",
        url: url_,
        headers: {
            ..._requestConfigSendInvitation?.headers,
            "Content-Type": "application/json",
        }
    };

    return getAxios().request(options_).catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
            return _error.response;
        } else {
            throw _error;
        }
    }).then((_response: AxiosResponse) => {
        return processSendInvitation(_response);
    });
}

function processSendInvitation(response: AxiosResponse): Promise<void> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === "object") {
        for (let k in response.headers) {
            if (response.headers.hasOwnProperty(k)) {
                _headers[k] = response.headers[k];
            }
        }
    }
    if (status === 400) {
        const _responseText = response.data;
        let result400: any = null;
        let resultData400  = _responseText;
        result400 = Types.initValidationProblemDetails(resultData400);
        return throwException("A server side error occurred.", status, _responseText, _headers, result400);

    } else if (status === 200) {
        const _responseText = response.data;
        return Promise.resolve<void>(null as any);

    } else if (status !== 200 && status !== 204) {
        const _responseText = response.data;
        return throwException("An unexpected server error occurred.", status, _responseText, _headers);
    }
    return Promise.resolve<void>(null as any);
}

/**
 * Get all your invitations to teams for this assignment
 */
export function getAllInvitations(assignmentId: number, config?: AxiosRequestConfig | undefined): Promise<Types.InvitationDto[]> {
    let url_ = getBaseUrl() + "/api/team-assignment/{assignmentId}/teams/invitations";
    if (assignmentId === undefined || assignmentId === null)
      throw new Error("The parameter 'assignmentId' must be defined.");
    url_ = url_.replace("{assignmentId}", encodeURIComponent("" + assignmentId));
      url_ = url_.replace(/[?&]$/, "");

    let options_: AxiosRequestConfig = {
        ..._requestConfigGetAllInvitations,
        ...config,
        method: "GET",
        url: url_,
        headers: {
            ..._requestConfigGetAllInvitations?.headers,
            "Accept": "application/json"
        }
    };

    return getAxios().request(options_).catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
            return _error.response;
        } else {
            throw _error;
        }
    }).then((_response: AxiosResponse) => {
        return processGetAllInvitations(_response);
    });
}

function processGetAllInvitations(response: AxiosResponse): Promise<Types.InvitationDto[]> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === "object") {
        for (let k in response.headers) {
            if (response.headers.hasOwnProperty(k)) {
                _headers[k] = response.headers[k];
            }
        }
    }
    if (status === 400) {
        const _responseText = response.data;
        let result400: any = null;
        let resultData400  = _responseText;
        result400 = Types.initValidationProblemDetails(resultData400);
        return throwException("A server side error occurred.", status, _responseText, _headers, result400);

    } else if (status === 200) {
        const _responseText = response.data;
        let result200: any = null;
        let resultData200  = _responseText;
        if (Array.isArray(resultData200)) {
              result200 = resultData200.map(item => 
                Types.initInvitationDto(item)
              );
            }
        return Promise.resolve<Types.InvitationDto[]>(result200);

    } else if (status !== 200 && status !== 204) {
        const _responseText = response.data;
        return throwException("An unexpected server error occurred.", status, _responseText, _headers);
    }
    return Promise.resolve<Types.InvitationDto[]>(null as any);
}

/**
 * Accept invitation to the team
 */
export function acceptInvitation(invitationId: number, config?: AxiosRequestConfig | undefined): Promise<Types.TeamDto> {
    let url_ = getBaseUrl() + "/api/invitations/{invitationId}/accept";
    if (invitationId === undefined || invitationId === null)
      throw new Error("The parameter 'invitationId' must be defined.");
    url_ = url_.replace("{invitationId}", encodeURIComponent("" + invitationId));
      url_ = url_.replace(/[?&]$/, "");

    let options_: AxiosRequestConfig = {
        ..._requestConfigAcceptInvitation,
        ...config,
        method: "POST",
        url: url_,
        headers: {
            ..._requestConfigAcceptInvitation?.headers,
            "Accept": "application/json"
        }
    };

    return getAxios().request(options_).catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
            return _error.response;
        } else {
            throw _error;
        }
    }).then((_response: AxiosResponse) => {
        return processAcceptInvitation(_response);
    });
}

function processAcceptInvitation(response: AxiosResponse): Promise<Types.TeamDto> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === "object") {
        for (let k in response.headers) {
            if (response.headers.hasOwnProperty(k)) {
                _headers[k] = response.headers[k];
            }
        }
    }
    if (status === 400) {
        const _responseText = response.data;
        let result400: any = null;
        let resultData400  = _responseText;
        result400 = Types.initValidationProblemDetails(resultData400);
        return throwException("A server side error occurred.", status, _responseText, _headers, result400);

    } else if (status === 200) {
        const _responseText = response.data;
        let result200: any = null;
        let resultData200  = _responseText;
        result200 = Types.initTeamDto(resultData200);
        return Promise.resolve<Types.TeamDto>(result200);

    } else if (status !== 200 && status !== 204) {
        const _responseText = response.data;
        return throwException("An unexpected server error occurred.", status, _responseText, _headers);
    }
    return Promise.resolve<Types.TeamDto>(null as any);
}

/**
 * Decline invitation to the team
 */
export function declineInvitation(invitationId: number, config?: AxiosRequestConfig | undefined): Promise<void> {
    let url_ = getBaseUrl() + "/api/invitations/{invitationId}/decline";
    if (invitationId === undefined || invitationId === null)
      throw new Error("The parameter 'invitationId' must be defined.");
    url_ = url_.replace("{invitationId}", encodeURIComponent("" + invitationId));
      url_ = url_.replace(/[?&]$/, "");

    let options_: AxiosRequestConfig = {
        ..._requestConfigDeclineInvitation,
        ...config,
        method: "DELETE",
        url: url_,
        headers: {
            ..._requestConfigDeclineInvitation?.headers,
        }
    };

    return getAxios().request(options_).catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
            return _error.response;
        } else {
            throw _error;
        }
    }).then((_response: AxiosResponse) => {
        return processDeclineInvitation(_response);
    });
}

function processDeclineInvitation(response: AxiosResponse): Promise<void> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === "object") {
        for (let k in response.headers) {
            if (response.headers.hasOwnProperty(k)) {
                _headers[k] = response.headers[k];
            }
        }
    }
    if (status === 400) {
        const _responseText = response.data;
        let result400: any = null;
        let resultData400  = _responseText;
        result400 = Types.initValidationProblemDetails(resultData400);
        return throwException("A server side error occurred.", status, _responseText, _headers, result400);

    } else if (status === 200) {
        const _responseText = response.data;
        return Promise.resolve<void>(null as any);

    } else if (status !== 200 && status !== 204) {
        const _responseText = response.data;
        return throwException("An unexpected server error occurred.", status, _responseText, _headers);
    }
    return Promise.resolve<void>(null as any);
}
let _requestConfigSendInvitation: Partial<AxiosRequestConfig> | null;
export function getSendInvitationRequestConfig() {
  return _requestConfigSendInvitation;
}
export function setSendInvitationRequestConfig(value: Partial<AxiosRequestConfig>) {
  _requestConfigSendInvitation = value;
}
export function patchSendInvitationRequestConfig(patch: (value: Partial<AxiosRequestConfig>) => Partial<AxiosRequestConfig>) {
  _requestConfigSendInvitation = patch(_requestConfigSendInvitation ?? {});
}

let _requestConfigGetAllInvitations: Partial<AxiosRequestConfig> | null;
export function getGetAllInvitationsRequestConfig() {
  return _requestConfigGetAllInvitations;
}
export function setGetAllInvitationsRequestConfig(value: Partial<AxiosRequestConfig>) {
  _requestConfigGetAllInvitations = value;
}
export function patchGetAllInvitationsRequestConfig(patch: (value: Partial<AxiosRequestConfig>) => Partial<AxiosRequestConfig>) {
  _requestConfigGetAllInvitations = patch(_requestConfigGetAllInvitations ?? {});
}

let _requestConfigAcceptInvitation: Partial<AxiosRequestConfig> | null;
export function getAcceptInvitationRequestConfig() {
  return _requestConfigAcceptInvitation;
}
export function setAcceptInvitationRequestConfig(value: Partial<AxiosRequestConfig>) {
  _requestConfigAcceptInvitation = value;
}
export function patchAcceptInvitationRequestConfig(patch: (value: Partial<AxiosRequestConfig>) => Partial<AxiosRequestConfig>) {
  _requestConfigAcceptInvitation = patch(_requestConfigAcceptInvitation ?? {});
}

let _requestConfigDeclineInvitation: Partial<AxiosRequestConfig> | null;
export function getDeclineInvitationRequestConfig() {
  return _requestConfigDeclineInvitation;
}
export function setDeclineInvitationRequestConfig(value: Partial<AxiosRequestConfig>) {
  _requestConfigDeclineInvitation = value;
}
export function patchDeclineInvitationRequestConfig(patch: (value: Partial<AxiosRequestConfig>) => Partial<AxiosRequestConfig>) {
  _requestConfigDeclineInvitation = patch(_requestConfigDeclineInvitation ?? {});
}