//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.20.0.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming
import * as Types from '../api-client.types';
import { useQuery, useMutation } from '@tanstack/react-query';
import type { UseQueryResult, QueryFunctionContext, UseQueryOptions, QueryClient, QueryKey, MutationKey, UseMutationOptions, UseMutationResult, QueryMeta, MutationMeta } from '@tanstack/react-query';
import { trimArrayEnd, isParameterObject, getBaseUrl, addMetaToOptions } from './helpers';
import type { QueryMetaContextValue } from 'react-query-swagger';
import { QueryMetaContext } from 'react-query-swagger';
import { useContext } from 'react';
import * as Client from './InvitationClient'
export { Client };
import type { AxiosRequestConfig } from 'axios';

export type SendInvitationInvitationQueryParameters = {
  teamId: number ;
}

export type GetAllInvitationsInvitationQueryParameters = {
  assignmentId: number ;
}

export type AcceptInvitationInvitationQueryParameters = {
  invitationId: number ;
}

export type DeclineInvitationInvitationQueryParameters = {
  invitationId: number ;
}

export function sendInvitationUrl(teamId: number): string {
  let url_ = getBaseUrl() + "/api/teams/{teamId}/invite";
if (teamId === undefined || teamId === null)
  throw new Error("The parameter 'teamId' must be defined.");
url_ = url_.replace("{teamId}", encodeURIComponent("" + teamId));
  url_ = url_.replace(/[?&]$/, "");
  return url_;
}

export function sendInvitationMutationKey(teamId: number): MutationKey {
  return trimArrayEnd([
      'InvitationClient',
      'sendInvitation',
      teamId as any,
    ]);
}

/**
 * Invite user to join your team
 */
export function useSendInvitationMutation<TContext>(teamId: number, options?: Omit<UseMutationOptions<void, unknown, string, TContext>, 'mutationKey' | 'mutationFn'>): UseMutationResult<void, unknown, string, TContext> {
  const key = sendInvitationMutationKey(teamId);
  
  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);
  
  return useMutation({
    ...options,
    mutationFn: (studentId: string) => Client.sendInvitation(teamId, studentId),
    mutationKey: key,
  });
}
  
type SendInvitation__MutationParameters = SendInvitationInvitationQueryParameters & {
  studentId: string;
}

/**
 * Invite user to join your team
 */
export function useSendInvitationMutationWithParameters<TContext>(options?: Omit<UseMutationOptions<void, unknown, SendInvitation__MutationParameters, TContext>, 'mutationKey' | 'mutationFn'> & { parameters?: SendInvitationInvitationQueryParameters}): UseMutationResult<void, unknown, SendInvitation__MutationParameters, TContext> {
  const key = sendInvitationMutationKey(options?.parameters?.teamId!);
  
  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);
  
return useMutation({
  ...options, 
  mutationFn: (data: SendInvitation__MutationParameters) => Client.sendInvitation(data.teamId ?? options?.parameters?.teamId!, data.studentId),
  mutationKey: key,
});
}
  
export function getAllInvitationsUrl(assignmentId: number): string {
  let url_ = getBaseUrl() + "/api/team-assignment/{assignmentId}/teams/invitations";
if (assignmentId === undefined || assignmentId === null)
  throw new Error("The parameter 'assignmentId' must be defined.");
url_ = url_.replace("{assignmentId}", encodeURIComponent("" + assignmentId));
  url_ = url_.replace(/[?&]$/, "");
  return url_;
}

let getAllInvitationsDefaultOptions: Omit<UseQueryOptions<Types.InvitationDto[], unknown, Types.InvitationDto[]>, 'queryKey'> = {
  queryFn: __getAllInvitations,
};
export function getGetAllInvitationsDefaultOptions() {
  return getAllInvitationsDefaultOptions;
};
export function setGetAllInvitationsDefaultOptions(options: typeof getAllInvitationsDefaultOptions) {
  getAllInvitationsDefaultOptions = options;
}

export function getAllInvitationsQueryKey(assignmentId: number): QueryKey;
export function getAllInvitationsQueryKey(...params: any[]): QueryKey {
  if (params.length === 1 && isParameterObject(params[0])) {
    const { assignmentId,  } = params[0] as GetAllInvitationsInvitationQueryParameters;

    return trimArrayEnd([
        'InvitationClient',
        'getAllInvitations',
        assignmentId as any,
      ]);
  } else {
    return trimArrayEnd([
        'InvitationClient',
        'getAllInvitations',
        ...params
      ]);
  }
}
function __getAllInvitations(context: QueryFunctionContext) {
  return Client.getAllInvitations(
      context.queryKey[2] as number    );
}

export function useGetAllInvitationsQuery<TSelectData = Types.InvitationDto[], TError = unknown>(dto: GetAllInvitationsInvitationQueryParameters, options?: Omit<UseQueryOptions<Types.InvitationDto[], TError, TSelectData>, 'queryKey'>, axiosConfig?: Partial<AxiosRequestConfig>): UseQueryResult<TSelectData, TError>;
/**
 * Get all your invitations to teams for this assignment
 */
export function useGetAllInvitationsQuery<TSelectData = Types.InvitationDto[], TError = unknown>(assignmentId: number, options?: Omit<UseQueryOptions<Types.InvitationDto[], TError, TSelectData>, 'queryKey'>, axiosConfig?: Partial<AxiosRequestConfig>): UseQueryResult<TSelectData, TError>;
export function useGetAllInvitationsQuery<TSelectData = Types.InvitationDto[], TError = unknown>(...params: any []): UseQueryResult<TSelectData, TError> {
  let options: UseQueryOptions<Types.InvitationDto[], TError, TSelectData> | undefined = undefined;
  let axiosConfig: AxiosRequestConfig |undefined;
  let assignmentId: any = undefined;
  
  if (params.length > 0) {
    if (isParameterObject(params[0])) {
      ({ assignmentId,  } = params[0] as GetAllInvitationsInvitationQueryParameters);
      options = params[1];
      axiosConfig = params[2];
    } else {
      [assignmentId, options, axiosConfig] = params;
    }
  }

  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);
  if (axiosConfig) {
    options = options ?? { } as any;
    options!.meta = { ...options!.meta, axiosConfig };
  }

  return useQuery<Types.InvitationDto[], TError, TSelectData>({
    queryFn: __getAllInvitations,
    queryKey: getAllInvitationsQueryKey(assignmentId),
    ...getAllInvitationsDefaultOptions as unknown as Omit<UseQueryOptions<Types.InvitationDto[], TError, TSelectData>, 'queryKey'>,
    ...options,
  });
}
/**
 * Get all your invitations to teams for this assignment
 */
export function setGetAllInvitationsData(queryClient: QueryClient, updater: (data: Types.InvitationDto[] | undefined) => Types.InvitationDto[], assignmentId: number) {
  queryClient.setQueryData(getAllInvitationsQueryKey(assignmentId),
    updater
  );
}

/**
 * Get all your invitations to teams for this assignment
 */
export function setGetAllInvitationsDataByQueryId(queryClient: QueryClient, queryKey: QueryKey, updater: (data: Types.InvitationDto[] | undefined) => Types.InvitationDto[]) {
  queryClient.setQueryData(queryKey, updater);
}
    
export function acceptInvitationUrl(invitationId: number): string {
  let url_ = getBaseUrl() + "/api/invitations/{invitationId}/accept";
if (invitationId === undefined || invitationId === null)
  throw new Error("The parameter 'invitationId' must be defined.");
url_ = url_.replace("{invitationId}", encodeURIComponent("" + invitationId));
  url_ = url_.replace(/[?&]$/, "");
  return url_;
}

export function acceptInvitationMutationKey(invitationId: number): MutationKey {
  return trimArrayEnd([
      'InvitationClient',
      'acceptInvitation',
      invitationId as any,
    ]);
}

/**
 * Accept invitation to the team
 */
export function useAcceptInvitationMutation<TContext>(invitationId: number, options?: Omit<UseMutationOptions<Types.TeamDto, unknown, void, TContext>, 'mutationKey' | 'mutationFn'>): UseMutationResult<Types.TeamDto, unknown, void, TContext> {
  const key = acceptInvitationMutationKey(invitationId);
  
  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);
  
  return useMutation({
    ...options,
    mutationFn: () => Client.acceptInvitation(invitationId),
    mutationKey: key,
  });
}
  
type AcceptInvitation__MutationParameters = AcceptInvitationInvitationQueryParameters

/**
 * Accept invitation to the team
 */
export function useAcceptInvitationMutationWithParameters<TContext>(options?: Omit<UseMutationOptions<Types.TeamDto, unknown, AcceptInvitation__MutationParameters, TContext>, 'mutationKey' | 'mutationFn'> & { parameters?: AcceptInvitationInvitationQueryParameters}): UseMutationResult<Types.TeamDto, unknown, AcceptInvitation__MutationParameters, TContext> {
  const key = acceptInvitationMutationKey(options?.parameters?.invitationId!);
  
  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);
  
return useMutation({
  ...options, 
  mutationFn: (data: AcceptInvitation__MutationParameters) => Client.acceptInvitation(data.invitationId ?? options?.parameters?.invitationId!),
  mutationKey: key,
});
}
  
export function declineInvitationUrl(invitationId: number): string {
  let url_ = getBaseUrl() + "/api/invitations/{invitationId}/decline";
if (invitationId === undefined || invitationId === null)
  throw new Error("The parameter 'invitationId' must be defined.");
url_ = url_.replace("{invitationId}", encodeURIComponent("" + invitationId));
  url_ = url_.replace(/[?&]$/, "");
  return url_;
}

export function declineInvitationMutationKey(invitationId: number): MutationKey {
  return trimArrayEnd([
      'InvitationClient',
      'declineInvitation',
      invitationId as any,
    ]);
}

/**
 * Decline invitation to the team
 */
export function useDeclineInvitationMutation<TContext>(invitationId: number, options?: Omit<UseMutationOptions<void, unknown, void, TContext>, 'mutationKey' | 'mutationFn'>): UseMutationResult<void, unknown, void, TContext> {
  const key = declineInvitationMutationKey(invitationId);
  
  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);
  
  return useMutation({
    ...options,
    mutationFn: () => Client.declineInvitation(invitationId),
    mutationKey: key,
  });
}
  
type DeclineInvitation__MutationParameters = DeclineInvitationInvitationQueryParameters

/**
 * Decline invitation to the team
 */
export function useDeclineInvitationMutationWithParameters<TContext>(options?: Omit<UseMutationOptions<void, unknown, DeclineInvitation__MutationParameters, TContext>, 'mutationKey' | 'mutationFn'> & { parameters?: DeclineInvitationInvitationQueryParameters}): UseMutationResult<void, unknown, DeclineInvitation__MutationParameters, TContext> {
  const key = declineInvitationMutationKey(options?.parameters?.invitationId!);
  
  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);
  
return useMutation({
  ...options, 
  mutationFn: (data: DeclineInvitation__MutationParameters) => Client.declineInvitation(data.invitationId ?? options?.parameters?.invitationId!),
  mutationKey: key,
});
}