//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.20.0.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming
import * as Types from '../api-client.types';
import { useQuery, useMutation } from '@tanstack/react-query';
import type { UseQueryResult, QueryFunctionContext, UseQueryOptions, QueryClient, QueryKey, MutationKey, UseMutationOptions, UseMutationResult, QueryMeta, MutationMeta } from '@tanstack/react-query';
import { trimArrayEnd, isParameterObject, getBaseUrl, addMetaToOptions } from './helpers';
import type { QueryMetaContextValue } from 'react-query-swagger';
import { QueryMetaContext } from 'react-query-swagger';
import { useContext } from 'react';
import * as Client from './PeerReviewClient'
export { Client };
import type { AxiosRequestConfig } from 'axios';

export type GetMappingsPeerReviewQueryParameters = {
  assignmentId: number ;
}

export type UpdateMappingsPeerReviewQueryParameters = {
  assignmentId: number ;
}

export type RegenerateMappingsPeerReviewQueryParameters = {
  assignmentId: number ;
}

export function getMappingsUrl(assignmentId: number): string {
  let url_ = getBaseUrl() + "/api/assignments/{assignmentId}/peer-review/mappings";
if (assignmentId === undefined || assignmentId === null)
  throw new Error("The parameter 'assignmentId' must be defined.");
url_ = url_.replace("{assignmentId}", encodeURIComponent("" + assignmentId));
  url_ = url_.replace(/[?&]$/, "");
  return url_;
}

let getMappingsDefaultOptions: Omit<UseQueryOptions<Types.PeerReviewMappingDto[], unknown, Types.PeerReviewMappingDto[]>, 'queryKey'> = {
  queryFn: __getMappings,
};
export function getGetMappingsDefaultOptions() {
  return getMappingsDefaultOptions;
};
export function setGetMappingsDefaultOptions(options: typeof getMappingsDefaultOptions) {
  getMappingsDefaultOptions = options;
}

export function getMappingsQueryKey(assignmentId: number): QueryKey;
export function getMappingsQueryKey(...params: any[]): QueryKey {
  if (params.length === 1 && isParameterObject(params[0])) {
    const { assignmentId,  } = params[0] as GetMappingsPeerReviewQueryParameters;

    return trimArrayEnd([
        'PeerReviewClient',
        'getMappings',
        assignmentId as any,
      ]);
  } else {
    return trimArrayEnd([
        'PeerReviewClient',
        'getMappings',
        ...params
      ]);
  }
}
function __getMappings(context: QueryFunctionContext) {
  return Client.getMappings(
      context.queryKey[2] as number    );
}

export function useGetMappingsQuery<TSelectData = Types.PeerReviewMappingDto[], TError = unknown>(dto: GetMappingsPeerReviewQueryParameters, options?: Omit<UseQueryOptions<Types.PeerReviewMappingDto[], TError, TSelectData>, 'queryKey'>, axiosConfig?: Partial<AxiosRequestConfig>): UseQueryResult<TSelectData, TError>;

export function useGetMappingsQuery<TSelectData = Types.PeerReviewMappingDto[], TError = unknown>(assignmentId: number, options?: Omit<UseQueryOptions<Types.PeerReviewMappingDto[], TError, TSelectData>, 'queryKey'>, axiosConfig?: Partial<AxiosRequestConfig>): UseQueryResult<TSelectData, TError>;
export function useGetMappingsQuery<TSelectData = Types.PeerReviewMappingDto[], TError = unknown>(...params: any []): UseQueryResult<TSelectData, TError> {
  let options: UseQueryOptions<Types.PeerReviewMappingDto[], TError, TSelectData> | undefined = undefined;
  let axiosConfig: AxiosRequestConfig |undefined;
  let assignmentId: any = undefined;
  
  if (params.length > 0) {
    if (isParameterObject(params[0])) {
      ({ assignmentId,  } = params[0] as GetMappingsPeerReviewQueryParameters);
      options = params[1];
      axiosConfig = params[2];
    } else {
      [assignmentId, options, axiosConfig] = params;
    }
  }

  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);
  if (axiosConfig) {
    options = options ?? { } as any;
    options!.meta = { ...options!.meta, axiosConfig };
  }

  return useQuery<Types.PeerReviewMappingDto[], TError, TSelectData>({
    queryFn: __getMappings,
    queryKey: getMappingsQueryKey(assignmentId),
    ...getMappingsDefaultOptions as unknown as Omit<UseQueryOptions<Types.PeerReviewMappingDto[], TError, TSelectData>, 'queryKey'>,
    ...options,
  });
}

export function setGetMappingsData(queryClient: QueryClient, updater: (data: Types.PeerReviewMappingDto[] | undefined) => Types.PeerReviewMappingDto[], assignmentId: number) {
  queryClient.setQueryData(getMappingsQueryKey(assignmentId),
    updater
  );
}

export function setGetMappingsDataByQueryId(queryClient: QueryClient, queryKey: QueryKey, updater: (data: Types.PeerReviewMappingDto[] | undefined) => Types.PeerReviewMappingDto[]) {
  queryClient.setQueryData(queryKey, updater);
}
    
export function updateMappingsUrl(assignmentId: number): string {
  let url_ = getBaseUrl() + "/api/assignments/{assignmentId}/peer-review/mappings";
if (assignmentId === undefined || assignmentId === null)
  throw new Error("The parameter 'assignmentId' must be defined.");
url_ = url_.replace("{assignmentId}", encodeURIComponent("" + assignmentId));
  url_ = url_.replace(/[?&]$/, "");
  return url_;
}

export function updateMappingsMutationKey(assignmentId: number): MutationKey {
  return trimArrayEnd([
      'PeerReviewClient',
      'updateMappings',
      assignmentId as any,
    ]);
}

export function useUpdateMappingsMutation<TContext>(assignmentId: number, options?: Omit<UseMutationOptions<void, unknown, Types.UpdatePeerReviewMappingsDto, TContext>, 'mutationKey' | 'mutationFn'>): UseMutationResult<void, unknown, Types.UpdatePeerReviewMappingsDto, TContext> {
  const key = updateMappingsMutationKey(assignmentId);
  
  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);
  
  return useMutation({
    ...options,
    mutationFn: (dto: Types.UpdatePeerReviewMappingsDto) => Client.updateMappings(assignmentId, dto),
    mutationKey: key,
  });
}
  
type UpdateMappings__MutationParameters = UpdateMappingsPeerReviewQueryParameters & {
  dto: Types.UpdatePeerReviewMappingsDto;
}

export function useUpdateMappingsMutationWithParameters<TContext>(options?: Omit<UseMutationOptions<void, unknown, UpdateMappings__MutationParameters, TContext>, 'mutationKey' | 'mutationFn'> & { parameters?: UpdateMappingsPeerReviewQueryParameters}): UseMutationResult<void, unknown, UpdateMappings__MutationParameters, TContext> {
  const key = updateMappingsMutationKey(options?.parameters?.assignmentId!);
  
  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);
  
return useMutation({
  ...options, 
  mutationFn: (data: UpdateMappings__MutationParameters) => Client.updateMappings(data.assignmentId ?? options?.parameters?.assignmentId!, data.dto),
  mutationKey: key,
});
}
  
export function regenerateMappingsUrl(assignmentId: number): string {
  let url_ = getBaseUrl() + "/api/assignments/{assignmentId}/peer-review/regenerate";
if (assignmentId === undefined || assignmentId === null)
  throw new Error("The parameter 'assignmentId' must be defined.");
url_ = url_.replace("{assignmentId}", encodeURIComponent("" + assignmentId));
  url_ = url_.replace(/[?&]$/, "");
  return url_;
}

export function regenerateMappingsMutationKey(assignmentId: number): MutationKey {
  return trimArrayEnd([
      'PeerReviewClient',
      'regenerateMappings',
      assignmentId as any,
    ]);
}

export function useRegenerateMappingsMutation<TContext>(assignmentId: number, options?: Omit<UseMutationOptions<void, unknown, void, TContext>, 'mutationKey' | 'mutationFn'>): UseMutationResult<void, unknown, void, TContext> {
  const key = regenerateMappingsMutationKey(assignmentId);
  
  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);
  
  return useMutation({
    ...options,
    mutationFn: () => Client.regenerateMappings(assignmentId),
    mutationKey: key,
  });
}
  
type RegenerateMappings__MutationParameters = RegenerateMappingsPeerReviewQueryParameters

export function useRegenerateMappingsMutationWithParameters<TContext>(options?: Omit<UseMutationOptions<void, unknown, RegenerateMappings__MutationParameters, TContext>, 'mutationKey' | 'mutationFn'> & { parameters?: RegenerateMappingsPeerReviewQueryParameters}): UseMutationResult<void, unknown, RegenerateMappings__MutationParameters, TContext> {
  const key = regenerateMappingsMutationKey(options?.parameters?.assignmentId!);
  
  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);
  
return useMutation({
  ...options, 
  mutationFn: (data: RegenerateMappings__MutationParameters) => Client.regenerateMappings(data.assignmentId ?? options?.parameters?.assignmentId!),
  mutationKey: key,
});
}

export function getPeerReviewAssignmentsQueryKey(assignmentId: number): QueryKey {
  return trimArrayEnd(['PeerReviewClient', 'getPeerReviewAssignments', assignmentId as any]);
}

export function useGetPeerReviewAssignmentsQuery(assignmentId: number, options?: Omit<UseQueryOptions<Types.PeerReviewAssignmentDto[], unknown, Types.PeerReviewAssignmentDto[]>, 'queryKey' | 'queryFn'>) {
  const metaContext = useContext(QueryMetaContext);
  const opts = addMetaToOptions(options, metaContext);
  return useQuery<Types.PeerReviewAssignmentDto[], unknown, Types.PeerReviewAssignmentDto[]>({
    queryKey: getPeerReviewAssignmentsQueryKey(assignmentId),
    queryFn: () => Client.getPeerReviewAssignments(assignmentId),
    ...opts,
  });
}

export function useCreatePeerReviewMutation(peerReviewAssignmentId: number, options?: Omit<UseMutationOptions<Types.PeerReviewDto, unknown, Types.CreatePeerReviewDto>, 'mutationKey' | 'mutationFn'>) {
  const metaContext = useContext(QueryMetaContext);
  const opts = addMetaToOptions(options, metaContext);
  return useMutation<Types.PeerReviewDto, unknown, Types.CreatePeerReviewDto>({
    ...opts,
    mutationFn: (dto: Types.CreatePeerReviewDto) => Client.createPeerReview(peerReviewAssignmentId, dto),
    mutationKey: trimArrayEnd(['PeerReviewClient', 'createPeerReview', peerReviewAssignmentId as any]),
  });
}

export function useDeletePeerReviewMutation(id: number, options?: Omit<UseMutationOptions<void, unknown, void>, 'mutationKey' | 'mutationFn'>) {
  const metaContext = useContext(QueryMetaContext);
  const opts = addMetaToOptions(options, metaContext);
  return useMutation<void, unknown, void>({
    ...opts,
    mutationFn: () => Client.deletePeerReview(id),
    mutationKey: trimArrayEnd(['PeerReviewClient', 'deletePeerReview', id as any]),
  });
}