//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.20.0.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming
import * as Types from '../api-client.types';
import type { AxiosRequestConfig, AxiosResponse, CancelToken } from 'axios';

import { throwException, isAxiosError } from '../api-client.types';
import { getAxios, getBaseUrl } from './helpers';

export function getMappings(assignmentId: number, config?: AxiosRequestConfig | undefined): Promise<Types.PeerReviewMappingDto[]> {
    let url_ = getBaseUrl() + "/api/assignments/{assignmentId}/peer-review/mappings";
    if (assignmentId === undefined || assignmentId === null)
      throw new Error("The parameter 'assignmentId' must be defined.");
    url_ = url_.replace("{assignmentId}", encodeURIComponent("" + assignmentId));
      url_ = url_.replace(/[?&]$/, "");

    let options_: AxiosRequestConfig = {
        ..._requestConfigGetMappings,
        ...config,
        method: "GET",
        url: url_,
        headers: {
            ..._requestConfigGetMappings?.headers,
            "Accept": "application/json"
        }
    };

    return getAxios().request(options_).catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
            return _error.response;
        } else {
            throw _error;
        }
    }).then((_response: AxiosResponse) => {
        return processGetMappings(_response);
    });
}

function processGetMappings(response: AxiosResponse): Promise<Types.PeerReviewMappingDto[]> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === "object") {
        for (let k in response.headers) {
            if (response.headers.hasOwnProperty(k)) {
                _headers[k] = response.headers[k];
            }
        }
    }
    if (status === 400) {
        const _responseText = response.data;
        let result400: any = null;
        let resultData400  = _responseText;
        result400 = Types.initValidationProblemDetails(resultData400);
        return throwException("A server side error occurred.", status, _responseText, _headers, result400);

    } else if (status === 200) {
        const _responseText = response.data;
        let result200: any = null;
        let resultData200  = _responseText;
        if (Array.isArray(resultData200)) {
              result200 = resultData200.map(item => 
                Types.initPeerReviewMappingDto(item)
              );
            }
        return Promise.resolve<Types.PeerReviewMappingDto[]>(result200);

    } else if (status !== 200 && status !== 204) {
        const _responseText = response.data;
        return throwException("An unexpected server error occurred.", status, _responseText, _headers);
    }
    return Promise.resolve<Types.PeerReviewMappingDto[]>(null as any);
}

export function updateMappings(assignmentId: number, dto: Types.UpdatePeerReviewMappingsDto, config?: AxiosRequestConfig | undefined): Promise<void> {
    let url_ = getBaseUrl() + "/api/assignments/{assignmentId}/peer-review/mappings";
    if (assignmentId === undefined || assignmentId === null)
      throw new Error("The parameter 'assignmentId' must be defined.");
    url_ = url_.replace("{assignmentId}", encodeURIComponent("" + assignmentId));
      url_ = url_.replace(/[?&]$/, "");

    const content_ = Types.serializeUpdatePeerReviewMappingsDto(dto);

    let options_: AxiosRequestConfig = {
        ..._requestConfigUpdateMappings,
        ...config,
        data: content_,
        method: "PUT",
        url: url_,
        headers: {
            ..._requestConfigUpdateMappings?.headers,
            "Content-Type": "application/json",
        }
    };

    return getAxios().request(options_).catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
            return _error.response;
        } else {
            throw _error;
        }
    }).then((_response: AxiosResponse) => {
        return processUpdateMappings(_response);
    });
}

function processUpdateMappings(response: AxiosResponse): Promise<void> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === "object") {
        for (let k in response.headers) {
            if (response.headers.hasOwnProperty(k)) {
                _headers[k] = response.headers[k];
            }
        }
    }
    if (status === 400) {
        const _responseText = response.data;
        let result400: any = null;
        let resultData400  = _responseText;
        result400 = Types.initValidationProblemDetails(resultData400);
        return throwException("A server side error occurred.", status, _responseText, _headers, result400);

    } else if (status === 200) {
        const _responseText = response.data;
        return Promise.resolve<void>(null as any);

    } else if (status !== 200 && status !== 204) {
        const _responseText = response.data;
        return throwException("An unexpected server error occurred.", status, _responseText, _headers);
    }
    return Promise.resolve<void>(null as any);
}

export function regenerateMappings(assignmentId: number, config?: AxiosRequestConfig | undefined): Promise<void> {
    let url_ = getBaseUrl() + "/api/assignments/{assignmentId}/peer-review/regenerate";
    if (assignmentId === undefined || assignmentId === null)
      throw new Error("The parameter 'assignmentId' must be defined.");
    url_ = url_.replace("{assignmentId}", encodeURIComponent("" + assignmentId));
      url_ = url_.replace(/[?&]$/, "");

    let options_: AxiosRequestConfig = {
        ..._requestConfigRegenerateMappings,
        ...config,
        method: "POST",
        url: url_,
        headers: {
            ..._requestConfigRegenerateMappings?.headers,
        }
    };

    return getAxios().request(options_).catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
            return _error.response;
        } else {
            throw _error;
        }
    }).then((_response: AxiosResponse) => {
        return processRegenerateMappings(_response);
    });
}

function processRegenerateMappings(response: AxiosResponse): Promise<void> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === "object") {
        for (let k in response.headers) {
            if (response.headers.hasOwnProperty(k)) {
                _headers[k] = response.headers[k];
            }
        }
    }
    if (status === 400) {
        const _responseText = response.data;
        let result400: any = null;
        let resultData400  = _responseText;
        result400 = Types.initValidationProblemDetails(resultData400);
        return throwException("A server side error occurred.", status, _responseText, _headers, result400);

    } else if (status === 200) {
        const _responseText = response.data;
        return Promise.resolve<void>(null as any);

    } else if (status !== 200 && status !== 204) {
        const _responseText = response.data;
        return throwException("An unexpected server error occurred.", status, _responseText, _headers);
    }
    return Promise.resolve<void>(null as any);
}

/**
 * Submit peer review
 */
export function createPeerReview(id: number, reviewDto: Types.CreatePeerReviewDto, config?: AxiosRequestConfig | undefined): Promise<Types.PeerReviewDto> {
    let url_ = getBaseUrl() + "/api/peer-review-assignment/{id}";
    if (id === undefined || id === null)
      throw new Error("The parameter 'id' must be defined.");
    url_ = url_.replace("{id}", encodeURIComponent("" + id));
      url_ = url_.replace(/[?&]$/, "");

    const content_ = Types.serializeCreatePeerReviewDto(reviewDto);

    let options_: AxiosRequestConfig = {
        ..._requestConfigCreatePeerReview,
        ...config,
        data: content_,
        method: "POST",
        url: url_,
        headers: {
            ..._requestConfigCreatePeerReview?.headers,
            "Content-Type": "application/json",
            "Accept": "application/json"
        }
    };

    return getAxios().request(options_).catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
            return _error.response;
        } else {
            throw _error;
        }
    }).then((_response: AxiosResponse) => {
        return processCreatePeerReview(_response);
    });
}

function processCreatePeerReview(response: AxiosResponse): Promise<Types.PeerReviewDto> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === "object") {
        for (let k in response.headers) {
            if (response.headers.hasOwnProperty(k)) {
                _headers[k] = response.headers[k];
            }
        }
    }
    if (status === 400) {
        const _responseText = response.data;
        let result400: any = null;
        let resultData400  = _responseText;
        result400 = Types.initValidationProblemDetails(resultData400);
        return throwException("A server side error occurred.", status, _responseText, _headers, result400);

    } else if (status === 200) {
        const _responseText = response.data;
        let result200: any = null;
        let resultData200  = _responseText;
        result200 = Types.initPeerReviewDto(resultData200);
        return Promise.resolve<Types.PeerReviewDto>(result200);

    } else if (status !== 200 && status !== 204) {
        const _responseText = response.data;
        return throwException("An unexpected server error occurred.", status, _responseText, _headers);
    }
    return Promise.resolve<Types.PeerReviewDto>(null as any);
}

/**
 * Get peer review assignments
 */
export function getPeerReviewAssignments(id: number, assignmentId: string, config?: AxiosRequestConfig | undefined): Promise<Types.PeerReviewAssignmentDto[]> {
    let url_ = getBaseUrl() + "/api/assignments/{assignmentId}/peer-review";
    if (id === undefined || id === null)
      throw new Error("The parameter 'id' must be defined.");
    url_ = url_.replace("{id}", encodeURIComponent("" + id));
    if (assignmentId === undefined || assignmentId === null)
      throw new Error("The parameter 'assignmentId' must be defined.");
    url_ = url_.replace("{assignmentId}", encodeURIComponent("" + assignmentId));
      url_ = url_.replace(/[?&]$/, "");

    let options_: AxiosRequestConfig = {
        ..._requestConfigGetPeerReviewAssignments,
        ...config,
        method: "GET",
        url: url_,
        headers: {
            ..._requestConfigGetPeerReviewAssignments?.headers,
            "Accept": "application/json"
        }
    };

    return getAxios().request(options_).catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
            return _error.response;
        } else {
            throw _error;
        }
    }).then((_response: AxiosResponse) => {
        return processGetPeerReviewAssignments(_response);
    });
}

function processGetPeerReviewAssignments(response: AxiosResponse): Promise<Types.PeerReviewAssignmentDto[]> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === "object") {
        for (let k in response.headers) {
            if (response.headers.hasOwnProperty(k)) {
                _headers[k] = response.headers[k];
            }
        }
    }
    if (status === 400) {
        const _responseText = response.data;
        let result400: any = null;
        let resultData400  = _responseText;
        result400 = Types.initValidationProblemDetails(resultData400);
        return throwException("A server side error occurred.", status, _responseText, _headers, result400);

    } else if (status === 200) {
        const _responseText = response.data;
        let result200: any = null;
        let resultData200  = _responseText;
        if (Array.isArray(resultData200)) {
              result200 = resultData200.map(item => 
                Types.initPeerReviewAssignmentDto(item)
              );
            }
        return Promise.resolve<Types.PeerReviewAssignmentDto[]>(result200);

    } else if (status !== 200 && status !== 204) {
        const _responseText = response.data;
        return throwException("An unexpected server error occurred.", status, _responseText, _headers);
    }
    return Promise.resolve<Types.PeerReviewAssignmentDto[]>(null as any);
}

/**
 * Delete peer review
 */
export function deletePeerReview(id: number, config?: AxiosRequestConfig | undefined): Promise<void> {
    let url_ = getBaseUrl() + "/api/peer-review/{id}";
    if (id === undefined || id === null)
      throw new Error("The parameter 'id' must be defined.");
    url_ = url_.replace("{id}", encodeURIComponent("" + id));
      url_ = url_.replace(/[?&]$/, "");

    let options_: AxiosRequestConfig = {
        ..._requestConfigDeletePeerReview,
        ...config,
        method: "DELETE",
        url: url_,
        headers: {
            ..._requestConfigDeletePeerReview?.headers,
        }
    };

    return getAxios().request(options_).catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
            return _error.response;
        } else {
            throw _error;
        }
    }).then((_response: AxiosResponse) => {
        return processDeletePeerReview(_response);
    });
}

function processDeletePeerReview(response: AxiosResponse): Promise<void> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === "object") {
        for (let k in response.headers) {
            if (response.headers.hasOwnProperty(k)) {
                _headers[k] = response.headers[k];
            }
        }
    }
    if (status === 400) {
        const _responseText = response.data;
        let result400: any = null;
        let resultData400  = _responseText;
        result400 = Types.initValidationProblemDetails(resultData400);
        return throwException("A server side error occurred.", status, _responseText, _headers, result400);

    } else if (status === 200) {
        const _responseText = response.data;
        return Promise.resolve<void>(null as any);

    } else if (status !== 200 && status !== 204) {
        const _responseText = response.data;
        return throwException("An unexpected server error occurred.", status, _responseText, _headers);
    }
    return Promise.resolve<void>(null as any);
}

/**
 * Get general information about peer review for one defendant (for teachers)
 */
export function getPeerReviewsGeneral(assignmentId: number, defendantId: string, config?: AxiosRequestConfig | undefined): Promise<Types.PeerReviewAssignmentDto[]> {
    let url_ = getBaseUrl() + "/api/assignments/{assignmentId}/defendant/{defendantId}/peer-reviews";
    if (assignmentId === undefined || assignmentId === null)
      throw new Error("The parameter 'assignmentId' must be defined.");
    url_ = url_.replace("{assignmentId}", encodeURIComponent("" + assignmentId));
    if (defendantId === undefined || defendantId === null)
      throw new Error("The parameter 'defendantId' must be defined.");
    url_ = url_.replace("{defendantId}", encodeURIComponent("" + defendantId));
      url_ = url_.replace(/[?&]$/, "");

    let options_: AxiosRequestConfig = {
        ..._requestConfigGetPeerReviewsGeneral,
        ...config,
        method: "GET",
        url: url_,
        headers: {
            ..._requestConfigGetPeerReviewsGeneral?.headers,
            "Accept": "application/json"
        }
    };

    return getAxios().request(options_).catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
            return _error.response;
        } else {
            throw _error;
        }
    }).then((_response: AxiosResponse) => {
        return processGetPeerReviewsGeneral(_response);
    });
}

function processGetPeerReviewsGeneral(response: AxiosResponse): Promise<Types.PeerReviewAssignmentDto[]> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === "object") {
        for (let k in response.headers) {
            if (response.headers.hasOwnProperty(k)) {
                _headers[k] = response.headers[k];
            }
        }
    }
    if (status === 400) {
        const _responseText = response.data;
        let result400: any = null;
        let resultData400  = _responseText;
        result400 = Types.initValidationProblemDetails(resultData400);
        return throwException("A server side error occurred.", status, _responseText, _headers, result400);

    } else if (status === 200) {
        const _responseText = response.data;
        let result200: any = null;
        let resultData200  = _responseText;
        if (Array.isArray(resultData200)) {
              result200 = resultData200.map(item => 
                Types.initPeerReviewAssignmentDto(item)
              );
            }
        return Promise.resolve<Types.PeerReviewAssignmentDto[]>(result200);

    } else if (status !== 200 && status !== 204) {
        const _responseText = response.data;
        return throwException("An unexpected server error occurred.", status, _responseText, _headers);
    }
    return Promise.resolve<Types.PeerReviewAssignmentDto[]>(null as any);
}

/**
 * Get full review information by review id
 */
export function getPeerReview(id: number, config?: AxiosRequestConfig | undefined): Promise<Types.PeerReviewDto> {
    let url_ = getBaseUrl() + "/api/peer-reviews/{id}";
    if (id === undefined || id === null)
      throw new Error("The parameter 'id' must be defined.");
    url_ = url_.replace("{id}", encodeURIComponent("" + id));
      url_ = url_.replace(/[?&]$/, "");

    let options_: AxiosRequestConfig = {
        ..._requestConfigGetPeerReview,
        ...config,
        method: "GET",
        url: url_,
        headers: {
            ..._requestConfigGetPeerReview?.headers,
            "Accept": "application/json"
        }
    };

    return getAxios().request(options_).catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
            return _error.response;
        } else {
            throw _error;
        }
    }).then((_response: AxiosResponse) => {
        return processGetPeerReview(_response);
    });
}

function processGetPeerReview(response: AxiosResponse): Promise<Types.PeerReviewDto> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === "object") {
        for (let k in response.headers) {
            if (response.headers.hasOwnProperty(k)) {
                _headers[k] = response.headers[k];
            }
        }
    }
    if (status === 400) {
        const _responseText = response.data;
        let result400: any = null;
        let resultData400  = _responseText;
        result400 = Types.initValidationProblemDetails(resultData400);
        return throwException("A server side error occurred.", status, _responseText, _headers, result400);

    } else if (status === 200) {
        const _responseText = response.data;
        let result200: any = null;
        let resultData200  = _responseText;
        result200 = Types.initPeerReviewDto(resultData200);
        return Promise.resolve<Types.PeerReviewDto>(result200);

    } else if (status !== 200 && status !== 204) {
        const _responseText = response.data;
        return throwException("An unexpected server error occurred.", status, _responseText, _headers);
    }
    return Promise.resolve<Types.PeerReviewDto>(null as any);
}

/**
 * Update review
 */
export function updatePeerReview(id: number, dto: Types.UpdatePeerReviewDto, config?: AxiosRequestConfig | undefined): Promise<Types.PeerReviewDto> {
    let url_ = getBaseUrl() + "/api/peer-reviews/{id}";
    if (id === undefined || id === null)
      throw new Error("The parameter 'id' must be defined.");
    url_ = url_.replace("{id}", encodeURIComponent("" + id));
      url_ = url_.replace(/[?&]$/, "");

    const content_ = Types.serializeUpdatePeerReviewDto(dto);

    let options_: AxiosRequestConfig = {
        ..._requestConfigUpdatePeerReview,
        ...config,
        data: content_,
        method: "PUT",
        url: url_,
        headers: {
            ..._requestConfigUpdatePeerReview?.headers,
            "Content-Type": "application/json",
            "Accept": "application/json"
        }
    };

    return getAxios().request(options_).catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
            return _error.response;
        } else {
            throw _error;
        }
    }).then((_response: AxiosResponse) => {
        return processUpdatePeerReview(_response);
    });
}

function processUpdatePeerReview(response: AxiosResponse): Promise<Types.PeerReviewDto> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === "object") {
        for (let k in response.headers) {
            if (response.headers.hasOwnProperty(k)) {
                _headers[k] = response.headers[k];
            }
        }
    }
    if (status === 400) {
        const _responseText = response.data;
        let result400: any = null;
        let resultData400  = _responseText;
        result400 = Types.initValidationProblemDetails(resultData400);
        return throwException("A server side error occurred.", status, _responseText, _headers, result400);

    } else if (status === 200) {
        const _responseText = response.data;
        let result200: any = null;
        let resultData200  = _responseText;
        result200 = Types.initPeerReviewDto(resultData200);
        return Promise.resolve<Types.PeerReviewDto>(result200);

    } else if (status !== 200 && status !== 204) {
        const _responseText = response.data;
        return throwException("An unexpected server error occurred.", status, _responseText, _headers);
    }
    return Promise.resolve<Types.PeerReviewDto>(null as any);
}

/**
 * Get full review information by assignment id (for students)
 */
export function getReview(id: number, config?: AxiosRequestConfig | undefined): Promise<Types.PeerReviewDto> {
    let url_ = getBaseUrl() + "/api/peer-review-assignment/{id}/review";
    if (id === undefined || id === null)
      throw new Error("The parameter 'id' must be defined.");
    url_ = url_.replace("{id}", encodeURIComponent("" + id));
      url_ = url_.replace(/[?&]$/, "");

    let options_: AxiosRequestConfig = {
        ..._requestConfigGetReview,
        ...config,
        method: "GET",
        url: url_,
        headers: {
            ..._requestConfigGetReview?.headers,
            "Accept": "application/json"
        }
    };

    return getAxios().request(options_).catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
            return _error.response;
        } else {
            throw _error;
        }
    }).then((_response: AxiosResponse) => {
        return processGetReview(_response);
    });
}

function processGetReview(response: AxiosResponse): Promise<Types.PeerReviewDto> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === "object") {
        for (let k in response.headers) {
            if (response.headers.hasOwnProperty(k)) {
                _headers[k] = response.headers[k];
            }
        }
    }
    if (status === 400) {
        const _responseText = response.data;
        let result400: any = null;
        let resultData400  = _responseText;
        result400 = Types.initValidationProblemDetails(resultData400);
        return throwException("A server side error occurred.", status, _responseText, _headers, result400);

    } else if (status === 200) {
        const _responseText = response.data;
        let result200: any = null;
        let resultData200  = _responseText;
        result200 = Types.initPeerReviewDto(resultData200);
        return Promise.resolve<Types.PeerReviewDto>(result200);

    } else if (status !== 200 && status !== 204) {
        const _responseText = response.data;
        return throwException("An unexpected server error occurred.", status, _responseText, _headers);
    }
    return Promise.resolve<Types.PeerReviewDto>(null as any);
}
let _requestConfigGetMappings: Partial<AxiosRequestConfig> | null;
export function getGetMappingsRequestConfig() {
  return _requestConfigGetMappings;
}
export function setGetMappingsRequestConfig(value: Partial<AxiosRequestConfig>) {
  _requestConfigGetMappings = value;
}
export function patchGetMappingsRequestConfig(patch: (value: Partial<AxiosRequestConfig>) => Partial<AxiosRequestConfig>) {
  _requestConfigGetMappings = patch(_requestConfigGetMappings ?? {});
}

let _requestConfigUpdateMappings: Partial<AxiosRequestConfig> | null;
export function getUpdateMappingsRequestConfig() {
  return _requestConfigUpdateMappings;
}
export function setUpdateMappingsRequestConfig(value: Partial<AxiosRequestConfig>) {
  _requestConfigUpdateMappings = value;
}
export function patchUpdateMappingsRequestConfig(patch: (value: Partial<AxiosRequestConfig>) => Partial<AxiosRequestConfig>) {
  _requestConfigUpdateMappings = patch(_requestConfigUpdateMappings ?? {});
}

let _requestConfigRegenerateMappings: Partial<AxiosRequestConfig> | null;
export function getRegenerateMappingsRequestConfig() {
  return _requestConfigRegenerateMappings;
}
export function setRegenerateMappingsRequestConfig(value: Partial<AxiosRequestConfig>) {
  _requestConfigRegenerateMappings = value;
}
export function patchRegenerateMappingsRequestConfig(patch: (value: Partial<AxiosRequestConfig>) => Partial<AxiosRequestConfig>) {
  _requestConfigRegenerateMappings = patch(_requestConfigRegenerateMappings ?? {});
}

let _requestConfigCreatePeerReview: Partial<AxiosRequestConfig> | null;
export function getCreatePeerReviewRequestConfig() {
  return _requestConfigCreatePeerReview;
}
export function setCreatePeerReviewRequestConfig(value: Partial<AxiosRequestConfig>) {
  _requestConfigCreatePeerReview = value;
}
export function patchCreatePeerReviewRequestConfig(patch: (value: Partial<AxiosRequestConfig>) => Partial<AxiosRequestConfig>) {
  _requestConfigCreatePeerReview = patch(_requestConfigCreatePeerReview ?? {});
}

let _requestConfigGetPeerReviewAssignments: Partial<AxiosRequestConfig> | null;
export function getGetPeerReviewAssignmentsRequestConfig() {
  return _requestConfigGetPeerReviewAssignments;
}
export function setGetPeerReviewAssignmentsRequestConfig(value: Partial<AxiosRequestConfig>) {
  _requestConfigGetPeerReviewAssignments = value;
}
export function patchGetPeerReviewAssignmentsRequestConfig(patch: (value: Partial<AxiosRequestConfig>) => Partial<AxiosRequestConfig>) {
  _requestConfigGetPeerReviewAssignments = patch(_requestConfigGetPeerReviewAssignments ?? {});
}

let _requestConfigDeletePeerReview: Partial<AxiosRequestConfig> | null;
export function getDeletePeerReviewRequestConfig() {
  return _requestConfigDeletePeerReview;
}
export function setDeletePeerReviewRequestConfig(value: Partial<AxiosRequestConfig>) {
  _requestConfigDeletePeerReview = value;
}
export function patchDeletePeerReviewRequestConfig(patch: (value: Partial<AxiosRequestConfig>) => Partial<AxiosRequestConfig>) {
  _requestConfigDeletePeerReview = patch(_requestConfigDeletePeerReview ?? {});
}

let _requestConfigGetPeerReviewsGeneral: Partial<AxiosRequestConfig> | null;
export function getGetPeerReviewsGeneralRequestConfig() {
  return _requestConfigGetPeerReviewsGeneral;
}
export function setGetPeerReviewsGeneralRequestConfig(value: Partial<AxiosRequestConfig>) {
  _requestConfigGetPeerReviewsGeneral = value;
}
export function patchGetPeerReviewsGeneralRequestConfig(patch: (value: Partial<AxiosRequestConfig>) => Partial<AxiosRequestConfig>) {
  _requestConfigGetPeerReviewsGeneral = patch(_requestConfigGetPeerReviewsGeneral ?? {});
}

let _requestConfigGetPeerReview: Partial<AxiosRequestConfig> | null;
export function getGetPeerReviewRequestConfig() {
  return _requestConfigGetPeerReview;
}
export function setGetPeerReviewRequestConfig(value: Partial<AxiosRequestConfig>) {
  _requestConfigGetPeerReview = value;
}
export function patchGetPeerReviewRequestConfig(patch: (value: Partial<AxiosRequestConfig>) => Partial<AxiosRequestConfig>) {
  _requestConfigGetPeerReview = patch(_requestConfigGetPeerReview ?? {});
}

let _requestConfigUpdatePeerReview: Partial<AxiosRequestConfig> | null;
export function getUpdatePeerReviewRequestConfig() {
  return _requestConfigUpdatePeerReview;
}
export function setUpdatePeerReviewRequestConfig(value: Partial<AxiosRequestConfig>) {
  _requestConfigUpdatePeerReview = value;
}
export function patchUpdatePeerReviewRequestConfig(patch: (value: Partial<AxiosRequestConfig>) => Partial<AxiosRequestConfig>) {
  _requestConfigUpdatePeerReview = patch(_requestConfigUpdatePeerReview ?? {});
}

let _requestConfigGetReview: Partial<AxiosRequestConfig> | null;
export function getGetReviewRequestConfig() {
  return _requestConfigGetReview;
}
export function setGetReviewRequestConfig(value: Partial<AxiosRequestConfig>) {
  _requestConfigGetReview = value;
}
export function patchGetReviewRequestConfig(patch: (value: Partial<AxiosRequestConfig>) => Partial<AxiosRequestConfig>) {
  _requestConfigGetReview = patch(_requestConfigGetReview ?? {});
}