//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.20.0.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming
import * as Types from '../api-client.types';
import type { AxiosRequestConfig, AxiosResponse, CancelToken } from 'axios';

import { throwException, isAxiosError } from '../api-client.types';
import { getAxios, getBaseUrl } from './helpers';

export function getMappings(assignmentId: number, config?: AxiosRequestConfig | undefined): Promise<Types.PeerReviewMappingDto[]> {
    let url_ = getBaseUrl() + "/api/assignments/{assignmentId}/peer-review/mappings";
    if (assignmentId === undefined || assignmentId === null)
      throw new Error("The parameter 'assignmentId' must be defined.");
    url_ = url_.replace("{assignmentId}", encodeURIComponent("" + assignmentId));
      url_ = url_.replace(/[?&]$/, "");

    let options_: AxiosRequestConfig = {
        ..._requestConfigGetMappings,
        ...config,
        method: "GET",
        url: url_,
        headers: {
            ..._requestConfigGetMappings?.headers,
            "Accept": "application/json"
        }
    };

    return getAxios().request(options_).catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
            return _error.response;
        } else {
            throw _error;
        }
    }).then((_response: AxiosResponse) => {
        return processGetMappings(_response);
    });
}

function processGetMappings(response: AxiosResponse): Promise<Types.PeerReviewMappingDto[]> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === "object") {
        for (let k in response.headers) {
            if (response.headers.hasOwnProperty(k)) {
                _headers[k] = response.headers[k];
            }
        }
    }
    if (status === 400) {
        const _responseText = response.data;
        let result400: any = null;
        let resultData400  = _responseText;
        result400 = Types.initValidationProblemDetails(resultData400);
        return throwException("A server side error occurred.", status, _responseText, _headers, result400);

    } else if (status === 200) {
        const _responseText = response.data;
        let result200: any = null;
        let resultData200  = _responseText;
        if (Array.isArray(resultData200)) {
              result200 = resultData200.map(item => 
                Types.initPeerReviewMappingDto(item)
              );
            }
        return Promise.resolve<Types.PeerReviewMappingDto[]>(result200);

    } else if (status !== 200 && status !== 204) {
        const _responseText = response.data;
        return throwException("An unexpected server error occurred.", status, _responseText, _headers);
    }
    return Promise.resolve<Types.PeerReviewMappingDto[]>(null as any);
}

export function updateMappings(assignmentId: number, dto: Types.UpdatePeerReviewMappingsDto, config?: AxiosRequestConfig | undefined): Promise<void> {
    let url_ = getBaseUrl() + "/api/assignments/{assignmentId}/peer-review/mappings";
    if (assignmentId === undefined || assignmentId === null)
      throw new Error("The parameter 'assignmentId' must be defined.");
    url_ = url_.replace("{assignmentId}", encodeURIComponent("" + assignmentId));
      url_ = url_.replace(/[?&]$/, "");

    const content_ = Types.serializeUpdatePeerReviewMappingsDto(dto);

    let options_: AxiosRequestConfig = {
        ..._requestConfigUpdateMappings,
        ...config,
        data: content_,
        method: "PUT",
        url: url_,
        headers: {
            ..._requestConfigUpdateMappings?.headers,
            "Content-Type": "application/json",
        }
    };

    return getAxios().request(options_).catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
            return _error.response;
        } else {
            throw _error;
        }
    }).then((_response: AxiosResponse) => {
        return processUpdateMappings(_response);
    });
}

function processUpdateMappings(response: AxiosResponse): Promise<void> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === "object") {
        for (let k in response.headers) {
            if (response.headers.hasOwnProperty(k)) {
                _headers[k] = response.headers[k];
            }
        }
    }
    if (status === 400) {
        const _responseText = response.data;
        let result400: any = null;
        let resultData400  = _responseText;
        result400 = Types.initValidationProblemDetails(resultData400);
        return throwException("A server side error occurred.", status, _responseText, _headers, result400);

    } else if (status === 200) {
        const _responseText = response.data;
        return Promise.resolve<void>(null as any);

    } else if (status !== 200 && status !== 204) {
        const _responseText = response.data;
        return throwException("An unexpected server error occurred.", status, _responseText, _headers);
    }
    return Promise.resolve<void>(null as any);
}

export function regenerateMappings(assignmentId: number, config?: AxiosRequestConfig | undefined): Promise<void> {
    let url_ = getBaseUrl() + "/api/assignments/{assignmentId}/peer-review/regenerate";
    if (assignmentId === undefined || assignmentId === null)
      throw new Error("The parameter 'assignmentId' must be defined.");
    url_ = url_.replace("{assignmentId}", encodeURIComponent("" + assignmentId));
      url_ = url_.replace(/[?&]$/, "");

    let options_: AxiosRequestConfig = {
        ..._requestConfigRegenerateMappings,
        ...config,
        method: "POST",
        url: url_,
        headers: {
            ..._requestConfigRegenerateMappings?.headers,
        }
    };

    return getAxios().request(options_).catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
            return _error.response;
        } else {
            throw _error;
        }
    }).then((_response: AxiosResponse) => {
        return processRegenerateMappings(_response);
    });
}

function processRegenerateMappings(response: AxiosResponse): Promise<void> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === "object") {
        for (let k in response.headers) {
            if (response.headers.hasOwnProperty(k)) {
                _headers[k] = response.headers[k];
            }
        }
    }
    if (status === 400) {
        const _responseText = response.data;
        let result400: any = null;
        let resultData400  = _responseText;
        result400 = Types.initValidationProblemDetails(resultData400);
        return throwException("A server side error occurred.", status, _responseText, _headers, result400);

    } else if (status === 200) {
        const _responseText = response.data;
        return Promise.resolve<void>(null as any);

    } else if (status !== 200 && status !== 204) {
        const _responseText = response.data;
        return throwException("An unexpected server error occurred.", status, _responseText, _headers);
    }
    return Promise.resolve<void>(null as any);
}
let _requestConfigGetMappings: Partial<AxiosRequestConfig> | null;
export function getGetMappingsRequestConfig() {
  return _requestConfigGetMappings;
}
export function setGetMappingsRequestConfig(value: Partial<AxiosRequestConfig>) {
  _requestConfigGetMappings = value;
}
export function patchGetMappingsRequestConfig(patch: (value: Partial<AxiosRequestConfig>) => Partial<AxiosRequestConfig>) {
  _requestConfigGetMappings = patch(_requestConfigGetMappings ?? {});
}

let _requestConfigUpdateMappings: Partial<AxiosRequestConfig> | null;
export function getUpdateMappingsRequestConfig() {
  return _requestConfigUpdateMappings;
}
export function setUpdateMappingsRequestConfig(value: Partial<AxiosRequestConfig>) {
  _requestConfigUpdateMappings = value;
}
export function patchUpdateMappingsRequestConfig(patch: (value: Partial<AxiosRequestConfig>) => Partial<AxiosRequestConfig>) {
  _requestConfigUpdateMappings = patch(_requestConfigUpdateMappings ?? {});
}

let _requestConfigRegenerateMappings: Partial<AxiosRequestConfig> | null;
export function getRegenerateMappingsRequestConfig() {
  return _requestConfigRegenerateMappings;
}
export function setRegenerateMappingsRequestConfig(value: Partial<AxiosRequestConfig>) {
  _requestConfigRegenerateMappings = value;
}
export function patchRegenerateMappingsRequestConfig(patch: (value: Partial<AxiosRequestConfig>) => Partial<AxiosRequestConfig>) {
  _requestConfigRegenerateMappings = patch(_requestConfigRegenerateMappings ?? {});
}