//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.20.0.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming
import * as Types from '../api-client.types';
import type { AxiosRequestConfig, AxiosResponse, CancelToken } from 'axios';

import { throwException, isAxiosError } from '../api-client.types';
import { getAxios, getBaseUrl } from './helpers';

/**
 * @param publicationType (optional) 
 * @param offset (optional) Offset of list.
 * @param limit (optional) Number of requested records.
 * @param sortBy (optional) Field name for sorting in DB.
 * @param sortOrder (optional) Sort direction. Ascending or Descending.
 */
export function getPublications(courseId: number, publicationType?: Types.PublicationType | null | undefined, offset?: number | null | undefined, limit?: number | null | undefined, sortBy?: string | null | undefined, sortOrder?: Types.SortOrder | undefined, config?: AxiosRequestConfig | undefined): Promise<Types.PagedResultOfPublicationDto> {
    let url_ = getBaseUrl() + "/api/courses/{courseId}/publications?";
    if (courseId === undefined || courseId === null)
      throw new Error("The parameter 'courseId' must be defined.");
    url_ = url_.replace("{courseId}", encodeURIComponent("" + courseId));
    if (publicationType !== undefined && publicationType !== null)
        url_ += "PublicationType=" + encodeURIComponent("" + publicationType) + "&";
    if (offset !== undefined && offset !== null)
        url_ += "Offset=" + encodeURIComponent("" + offset) + "&";
    if (limit !== undefined && limit !== null)
        url_ += "Limit=" + encodeURIComponent("" + limit) + "&";
    if (sortBy !== undefined && sortBy !== null)
        url_ += "SortBy=" + encodeURIComponent("" + sortBy) + "&";
    if (sortOrder === null)
        throw new Error("The parameter 'sortOrder' cannot be null.");
    else if (sortOrder !== undefined)
        url_ += "SortOrder=" + encodeURIComponent("" + sortOrder) + "&";
      url_ = url_.replace(/[?&]$/, "");

    let options_: AxiosRequestConfig = {
        ..._requestConfigGetPublications,
        ...config,
        method: "GET",
        url: url_,
        headers: {
            ..._requestConfigGetPublications?.headers,
            "Accept": "application/json"
        }
    };

    return getAxios().request(options_).catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
            return _error.response;
        } else {
            throw _error;
        }
    }).then((_response: AxiosResponse) => {
        return processGetPublications(_response);
    });
}

function processGetPublications(response: AxiosResponse): Promise<Types.PagedResultOfPublicationDto> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === "object") {
        for (let k in response.headers) {
            if (response.headers.hasOwnProperty(k)) {
                _headers[k] = response.headers[k];
            }
        }
    }
    if (status === 400) {
        const _responseText = response.data;
        let result400: any = null;
        let resultData400  = _responseText;
        result400 = Types.initValidationProblemDetails(resultData400);
        return throwException("A server side error occurred.", status, _responseText, _headers, result400);

    } else if (status === 200) {
        const _responseText = response.data;
        let result200: any = null;
        let resultData200  = _responseText;
        result200 = Types.initPagedResultOfPublicationDto(resultData200);
        return Promise.resolve<Types.PagedResultOfPublicationDto>(result200);

    } else if (status !== 200 && status !== 204) {
        const _responseText = response.data;
        return throwException("An unexpected server error occurred.", status, _responseText, _headers);
    }
    return Promise.resolve<Types.PagedResultOfPublicationDto>(null as any);
}

export function getPublicationById(publicationId: number, config?: AxiosRequestConfig | undefined): Promise<Types.PublicationDto> {
    let url_ = getBaseUrl() + "/api/publications/{publicationId}";
    if (publicationId === undefined || publicationId === null)
      throw new Error("The parameter 'publicationId' must be defined.");
    url_ = url_.replace("{publicationId}", encodeURIComponent("" + publicationId));
      url_ = url_.replace(/[?&]$/, "");

    let options_: AxiosRequestConfig = {
        ..._requestConfigGetPublicationById,
        ...config,
        method: "GET",
        url: url_,
        headers: {
            ..._requestConfigGetPublicationById?.headers,
            "Accept": "application/json"
        }
    };

    return getAxios().request(options_).catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
            return _error.response;
        } else {
            throw _error;
        }
    }).then((_response: AxiosResponse) => {
        return processGetPublicationById(_response);
    });
}

function processGetPublicationById(response: AxiosResponse): Promise<Types.PublicationDto> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === "object") {
        for (let k in response.headers) {
            if (response.headers.hasOwnProperty(k)) {
                _headers[k] = response.headers[k];
            }
        }
    }
    if (status === 400) {
        const _responseText = response.data;
        let result400: any = null;
        let resultData400  = _responseText;
        result400 = Types.initValidationProblemDetails(resultData400);
        return throwException("A server side error occurred.", status, _responseText, _headers, result400);

    } else if (status === 200) {
        const _responseText = response.data;
        let result200: any = null;
        let resultData200  = _responseText;
        result200 = Types.initPublicationDto(resultData200);
        return Promise.resolve<Types.PublicationDto>(result200);

    } else if (status !== 200 && status !== 204) {
        const _responseText = response.data;
        return throwException("An unexpected server error occurred.", status, _responseText, _headers);
    }
    return Promise.resolve<Types.PublicationDto>(null as any);
}
let _requestConfigGetPublications: Partial<AxiosRequestConfig> | null;
export function getGetPublicationsRequestConfig() {
  return _requestConfigGetPublications;
}
export function setGetPublicationsRequestConfig(value: Partial<AxiosRequestConfig>) {
  _requestConfigGetPublications = value;
}
export function patchGetPublicationsRequestConfig(patch: (value: Partial<AxiosRequestConfig>) => Partial<AxiosRequestConfig>) {
  _requestConfigGetPublications = patch(_requestConfigGetPublications ?? {});
}

let _requestConfigGetPublicationById: Partial<AxiosRequestConfig> | null;
export function getGetPublicationByIdRequestConfig() {
  return _requestConfigGetPublicationById;
}
export function setGetPublicationByIdRequestConfig(value: Partial<AxiosRequestConfig>) {
  _requestConfigGetPublicationById = value;
}
export function patchGetPublicationByIdRequestConfig(patch: (value: Partial<AxiosRequestConfig>) => Partial<AxiosRequestConfig>) {
  _requestConfigGetPublicationById = patch(_requestConfigGetPublicationById ?? {});
}