//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.20.0.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming
import * as Types from '../api-client.types';
import { useQuery, useMutation } from '@tanstack/react-query';
import type { UseQueryResult, QueryFunctionContext, UseQueryOptions, QueryClient, QueryKey, MutationKey, UseMutationOptions, UseMutationResult, QueryMeta, MutationMeta } from '@tanstack/react-query';
import { trimArrayEnd, isParameterObject, getBaseUrl, addMetaToOptions } from './helpers';
import type { QueryMetaContextValue } from 'react-query-swagger';
import { QueryMetaContext } from 'react-query-swagger';
import { useContext } from 'react';
import * as Client from './SubmissionClient'
export { Client };
import type { AxiosRequestConfig } from 'axios';

export type CreateSubmissionSubmissionQueryParameters = {
  id: number ;
}

export type GetSubmissionsSubmissionQueryParameters = {
  id: number ;
  offset?: number | null | undefined ;
  limit?: number | null | undefined ;
  sortBy?: string | null | undefined ;
  sortOrder?: Types.SortOrder | undefined ;
}

export type GetMySubmissionSubmissionQueryParameters = {
  id: number ;
}

export type GetSubmissionSubmissionQueryParameters = {
  id: number ;
}

export type SaveDraftSubmissionQueryParameters = {
  id: number ;
}

export type RetractSubmissionSubmissionQueryParameters = {
  id: number ;
}

export type MarkSubmissionSubmissionQueryParameters = {
  id: number ;
}

export function createSubmissionUrl(id: number): string {
  let url_ = getBaseUrl() + "/api/assignments/{id}/submission";
if (id === undefined || id === null)
  throw new Error("The parameter 'id' must be defined.");
url_ = url_.replace("{id}", encodeURIComponent("" + id));
  url_ = url_.replace(/[?&]$/, "");
  return url_;
}

export function createSubmissionMutationKey(id: number): MutationKey {
  return trimArrayEnd([
      'SubmissionClient',
      'createSubmission',
      id as any,
    ]);
}

/**
 * Create submission
 */
export function useCreateSubmissionMutation<TContext>(id: number, options?: Omit<UseMutationOptions<Types.SubmissionDto, unknown, Types.CreateSubmissionDto, TContext>, 'mutationKey' | 'mutationFn'>): UseMutationResult<Types.SubmissionDto, unknown, Types.CreateSubmissionDto, TContext> {
  const key = createSubmissionMutationKey(id);
  
  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);
  
  return useMutation({
    ...options,
    mutationFn: (dto: Types.CreateSubmissionDto) => Client.createSubmission(id, dto),
    mutationKey: key,
  });
}
  
type CreateSubmission__MutationParameters = CreateSubmissionSubmissionQueryParameters & {
  dto: Types.CreateSubmissionDto;
}

/**
 * Create submission
 */
export function useCreateSubmissionMutationWithParameters<TContext>(options?: Omit<UseMutationOptions<Types.SubmissionDto, unknown, CreateSubmission__MutationParameters, TContext>, 'mutationKey' | 'mutationFn'> & { parameters?: CreateSubmissionSubmissionQueryParameters}): UseMutationResult<Types.SubmissionDto, unknown, CreateSubmission__MutationParameters, TContext> {
  const key = createSubmissionMutationKey(options?.parameters?.id!);
  
  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);
  
return useMutation({
  ...options, 
  mutationFn: (data: CreateSubmission__MutationParameters) => Client.createSubmission(data.id ?? options?.parameters?.id!, data.dto),
  mutationKey: key,
});
}
  
export function getSubmissionsUrl(id: number, offset?: number | null | undefined, limit?: number | null | undefined, sortBy?: string | null | undefined, sortOrder?: Types.SortOrder | undefined): string {
  let url_ = getBaseUrl() + "/api/assignments/{id}/submissions?";
if (id === undefined || id === null)
  throw new Error("The parameter 'id' must be defined.");
url_ = url_.replace("{id}", encodeURIComponent("" + id));
if (offset !== undefined && offset !== null)
    url_ += "Offset=" + encodeURIComponent("" + offset) + "&";
if (limit !== undefined && limit !== null)
    url_ += "Limit=" + encodeURIComponent("" + limit) + "&";
if (sortBy !== undefined && sortBy !== null)
    url_ += "SortBy=" + encodeURIComponent("" + sortBy) + "&";
if (sortOrder === null)
    throw new Error("The parameter 'sortOrder' cannot be null.");
else if (sortOrder !== undefined)
    url_ += "SortOrder=" + encodeURIComponent("" + sortOrder) + "&";
  url_ = url_.replace(/[?&]$/, "");
  return url_;
}

let getSubmissionsDefaultOptions: Omit<UseQueryOptions<Types.PagedResultOfSubmissionListItem, unknown, Types.PagedResultOfSubmissionListItem>, 'queryKey'> = {
  queryFn: __getSubmissions,
};
export function getGetSubmissionsDefaultOptions() {
  return getSubmissionsDefaultOptions;
};
export function setGetSubmissionsDefaultOptions(options: typeof getSubmissionsDefaultOptions) {
  getSubmissionsDefaultOptions = options;
}

export function getSubmissionsQueryKey(dto: GetSubmissionsSubmissionQueryParameters): QueryKey;
export function getSubmissionsQueryKey(id: number, offset?: number | null | undefined, limit?: number | null | undefined, sortBy?: string | null | undefined, sortOrder?: Types.SortOrder | undefined): QueryKey;
export function getSubmissionsQueryKey(...params: any[]): QueryKey {
  if (params.length === 1 && isParameterObject(params[0])) {
    const { id, offset, limit, sortBy, sortOrder,  } = params[0] as GetSubmissionsSubmissionQueryParameters;

    return trimArrayEnd([
        'SubmissionClient',
        'getSubmissions',
        id as any,
        offset as any,
        limit as any,
        sortBy as any,
        sortOrder as any,
      ]);
  } else {
    return trimArrayEnd([
        'SubmissionClient',
        'getSubmissions',
        ...params
      ]);
  }
}
function __getSubmissions(context: QueryFunctionContext) {
  return Client.getSubmissions(
      context.queryKey[2] as number,       context.queryKey[3] as number | null | undefined,       context.queryKey[4] as number | null | undefined,       context.queryKey[5] as string | null | undefined,       context.queryKey[6] as Types.SortOrder | undefined    );
}

export function useGetSubmissionsQuery<TSelectData = Types.PagedResultOfSubmissionListItem, TError = unknown>(dto: GetSubmissionsSubmissionQueryParameters, options?: Omit<UseQueryOptions<Types.PagedResultOfSubmissionListItem, TError, TSelectData>, 'queryKey'>, axiosConfig?: Partial<AxiosRequestConfig>): UseQueryResult<TSelectData, TError>;
/**
 * Gets all submissions for an assignment (check permission)
 * @param offset (optional) Offset of list.
 * @param limit (optional) Number of requested records.
 * @param sortBy (optional) Field name for sorting in DB.
 * @param sortOrder (optional) Sort direction. Ascending or Descending.
 */
export function useGetSubmissionsQuery<TSelectData = Types.PagedResultOfSubmissionListItem, TError = unknown>(id: number, offset?: number | null | undefined, limit?: number | null | undefined, sortBy?: string | null | undefined, sortOrder?: Types.SortOrder | undefined, options?: Omit<UseQueryOptions<Types.PagedResultOfSubmissionListItem, TError, TSelectData>, 'queryKey'>, axiosConfig?: Partial<AxiosRequestConfig>): UseQueryResult<TSelectData, TError>;
export function useGetSubmissionsQuery<TSelectData = Types.PagedResultOfSubmissionListItem, TError = unknown>(...params: any []): UseQueryResult<TSelectData, TError> {
  let options: UseQueryOptions<Types.PagedResultOfSubmissionListItem, TError, TSelectData> | undefined = undefined;
  let axiosConfig: AxiosRequestConfig |undefined;
  let id: any = undefined;
  let offset: any = undefined;
  let limit: any = undefined;
  let sortBy: any = undefined;
  let sortOrder: any = undefined;
  
  if (params.length > 0) {
    if (isParameterObject(params[0])) {
      ({ id, offset, limit, sortBy, sortOrder,  } = params[0] as GetSubmissionsSubmissionQueryParameters);
      options = params[1];
      axiosConfig = params[2];
    } else {
      [id, offset, limit, sortBy, sortOrder, options, axiosConfig] = params;
    }
  }

  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);
  if (axiosConfig) {
    options = options ?? { } as any;
    options!.meta = { ...options!.meta, axiosConfig };
  }

  return useQuery<Types.PagedResultOfSubmissionListItem, TError, TSelectData>({
    queryFn: __getSubmissions,
    queryKey: getSubmissionsQueryKey(id, offset, limit, sortBy, sortOrder),
    ...getSubmissionsDefaultOptions as unknown as Omit<UseQueryOptions<Types.PagedResultOfSubmissionListItem, TError, TSelectData>, 'queryKey'>,
    ...options,
  });
}
/**
 * Gets all submissions for an assignment (check permission)
 * @param offset (optional) Offset of list.
 * @param limit (optional) Number of requested records.
 * @param sortBy (optional) Field name for sorting in DB.
 * @param sortOrder (optional) Sort direction. Ascending or Descending.
 */
export function setGetSubmissionsData(queryClient: QueryClient, updater: (data: Types.PagedResultOfSubmissionListItem | undefined) => Types.PagedResultOfSubmissionListItem, id: number, offset?: number | null | undefined, limit?: number | null | undefined, sortBy?: string | null | undefined, sortOrder?: Types.SortOrder | undefined) {
  queryClient.setQueryData(getSubmissionsQueryKey(id, offset, limit, sortBy, sortOrder),
    updater
  );
}

/**
 * Gets all submissions for an assignment (check permission)
 * @param offset (optional) Offset of list.
 * @param limit (optional) Number of requested records.
 * @param sortBy (optional) Field name for sorting in DB.
 * @param sortOrder (optional) Sort direction. Ascending or Descending.
 */
export function setGetSubmissionsDataByQueryId(queryClient: QueryClient, queryKey: QueryKey, updater: (data: Types.PagedResultOfSubmissionListItem | undefined) => Types.PagedResultOfSubmissionListItem) {
  queryClient.setQueryData(queryKey, updater);
}
    
export function getMySubmissionUrl(id: number): string {
  let url_ = getBaseUrl() + "/api/assignments/{id}/my-submission";
if (id === undefined || id === null)
  throw new Error("The parameter 'id' must be defined.");
url_ = url_.replace("{id}", encodeURIComponent("" + id));
  url_ = url_.replace(/[?&]$/, "");
  return url_;
}

let getMySubmissionDefaultOptions: Omit<UseQueryOptions<Types.SubmissionDto, unknown, Types.SubmissionDto>, 'queryKey'> = {
  queryFn: __getMySubmission,
};
export function getGetMySubmissionDefaultOptions() {
  return getMySubmissionDefaultOptions;
};
export function setGetMySubmissionDefaultOptions(options: typeof getMySubmissionDefaultOptions) {
  getMySubmissionDefaultOptions = options;
}

export function getMySubmissionQueryKey(id: number): QueryKey;
export function getMySubmissionQueryKey(...params: any[]): QueryKey {
  if (params.length === 1 && isParameterObject(params[0])) {
    const { id,  } = params[0] as GetMySubmissionSubmissionQueryParameters;

    return trimArrayEnd([
        'SubmissionClient',
        'getMySubmission',
        id as any,
      ]);
  } else {
    return trimArrayEnd([
        'SubmissionClient',
        'getMySubmission',
        ...params
      ]);
  }
}
function __getMySubmission(context: QueryFunctionContext) {
  return Client.getMySubmission(
      context.queryKey[2] as number    );
}

export function useGetMySubmissionQuery<TSelectData = Types.SubmissionDto, TError = unknown>(dto: GetMySubmissionSubmissionQueryParameters, options?: Omit<UseQueryOptions<Types.SubmissionDto, TError, TSelectData>, 'queryKey'>, axiosConfig?: Partial<AxiosRequestConfig>): UseQueryResult<TSelectData, TError>;
/**
 * Gets student's submission for an assignment
 */
export function useGetMySubmissionQuery<TSelectData = Types.SubmissionDto, TError = unknown>(id: number, options?: Omit<UseQueryOptions<Types.SubmissionDto, TError, TSelectData>, 'queryKey'>, axiosConfig?: Partial<AxiosRequestConfig>): UseQueryResult<TSelectData, TError>;
export function useGetMySubmissionQuery<TSelectData = Types.SubmissionDto, TError = unknown>(...params: any []): UseQueryResult<TSelectData, TError> {
  let options: UseQueryOptions<Types.SubmissionDto, TError, TSelectData> | undefined = undefined;
  let axiosConfig: AxiosRequestConfig |undefined;
  let id: any = undefined;
  
  if (params.length > 0) {
    if (isParameterObject(params[0])) {
      ({ id,  } = params[0] as GetMySubmissionSubmissionQueryParameters);
      options = params[1];
      axiosConfig = params[2];
    } else {
      [id, options, axiosConfig] = params;
    }
  }

  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);
  if (axiosConfig) {
    options = options ?? { } as any;
    options!.meta = { ...options!.meta, axiosConfig };
  }

  return useQuery<Types.SubmissionDto, TError, TSelectData>({
    queryFn: __getMySubmission,
    queryKey: getMySubmissionQueryKey(id),
    ...getMySubmissionDefaultOptions as unknown as Omit<UseQueryOptions<Types.SubmissionDto, TError, TSelectData>, 'queryKey'>,
    ...options,
  });
}
/**
 * Gets student's submission for an assignment
 */
export function setGetMySubmissionData(queryClient: QueryClient, updater: (data: Types.SubmissionDto | undefined) => Types.SubmissionDto, id: number) {
  queryClient.setQueryData(getMySubmissionQueryKey(id),
    updater
  );
}

/**
 * Gets student's submission for an assignment
 */
export function setGetMySubmissionDataByQueryId(queryClient: QueryClient, queryKey: QueryKey, updater: (data: Types.SubmissionDto | undefined) => Types.SubmissionDto) {
  queryClient.setQueryData(queryKey, updater);
}
    
export function getSubmissionUrl(id: number): string {
  let url_ = getBaseUrl() + "/api/submissions/{id}";
if (id === undefined || id === null)
  throw new Error("The parameter 'id' must be defined.");
url_ = url_.replace("{id}", encodeURIComponent("" + id));
  url_ = url_.replace(/[?&]$/, "");
  return url_;
}

let getSubmissionDefaultOptions: Omit<UseQueryOptions<Types.SubmissionDto, unknown, Types.SubmissionDto>, 'queryKey'> = {
  queryFn: __getSubmission,
};
export function getGetSubmissionDefaultOptions() {
  return getSubmissionDefaultOptions;
};
export function setGetSubmissionDefaultOptions(options: typeof getSubmissionDefaultOptions) {
  getSubmissionDefaultOptions = options;
}

export function getSubmissionQueryKey(id: number): QueryKey;
export function getSubmissionQueryKey(...params: any[]): QueryKey {
  if (params.length === 1 && isParameterObject(params[0])) {
    const { id,  } = params[0] as GetSubmissionSubmissionQueryParameters;

    return trimArrayEnd([
        'SubmissionClient',
        'getSubmission',
        id as any,
      ]);
  } else {
    return trimArrayEnd([
        'SubmissionClient',
        'getSubmission',
        ...params
      ]);
  }
}
function __getSubmission(context: QueryFunctionContext) {
  return Client.getSubmission(
      context.queryKey[2] as number    );
}

export function useGetSubmissionQuery<TSelectData = Types.SubmissionDto, TError = unknown>(dto: GetSubmissionSubmissionQueryParameters, options?: Omit<UseQueryOptions<Types.SubmissionDto, TError, TSelectData>, 'queryKey'>, axiosConfig?: Partial<AxiosRequestConfig>): UseQueryResult<TSelectData, TError>;
/**
 * Gets full information for specific submission (check permission)
 */
export function useGetSubmissionQuery<TSelectData = Types.SubmissionDto, TError = unknown>(id: number, options?: Omit<UseQueryOptions<Types.SubmissionDto, TError, TSelectData>, 'queryKey'>, axiosConfig?: Partial<AxiosRequestConfig>): UseQueryResult<TSelectData, TError>;
export function useGetSubmissionQuery<TSelectData = Types.SubmissionDto, TError = unknown>(...params: any []): UseQueryResult<TSelectData, TError> {
  let options: UseQueryOptions<Types.SubmissionDto, TError, TSelectData> | undefined = undefined;
  let axiosConfig: AxiosRequestConfig |undefined;
  let id: any = undefined;
  
  if (params.length > 0) {
    if (isParameterObject(params[0])) {
      ({ id,  } = params[0] as GetSubmissionSubmissionQueryParameters);
      options = params[1];
      axiosConfig = params[2];
    } else {
      [id, options, axiosConfig] = params;
    }
  }

  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);
  if (axiosConfig) {
    options = options ?? { } as any;
    options!.meta = { ...options!.meta, axiosConfig };
  }

  return useQuery<Types.SubmissionDto, TError, TSelectData>({
    queryFn: __getSubmission,
    queryKey: getSubmissionQueryKey(id),
    ...getSubmissionDefaultOptions as unknown as Omit<UseQueryOptions<Types.SubmissionDto, TError, TSelectData>, 'queryKey'>,
    ...options,
  });
}
/**
 * Gets full information for specific submission (check permission)
 */
export function setGetSubmissionData(queryClient: QueryClient, updater: (data: Types.SubmissionDto | undefined) => Types.SubmissionDto, id: number) {
  queryClient.setQueryData(getSubmissionQueryKey(id),
    updater
  );
}

/**
 * Gets full information for specific submission (check permission)
 */
export function setGetSubmissionDataByQueryId(queryClient: QueryClient, queryKey: QueryKey, updater: (data: Types.SubmissionDto | undefined) => Types.SubmissionDto) {
  queryClient.setQueryData(queryKey, updater);
}
    
export function saveDraftUrl(id: number): string {
  let url_ = getBaseUrl() + "/api/assignments/{id}/submission/draft";
if (id === undefined || id === null)
  throw new Error("The parameter 'id' must be defined.");
url_ = url_.replace("{id}", encodeURIComponent("" + id));
  url_ = url_.replace(/[?&]$/, "");
  return url_;
}

export function saveDraftMutationKey(id: number): MutationKey {
  return trimArrayEnd([
      'SubmissionClient',
      'saveDraft',
      id as any,
    ]);
}

/**
 * Save (upsert) draft submission
 */
export function useSaveDraftMutation<TContext>(id: number, options?: Omit<UseMutationOptions<Types.SubmissionDto, unknown, Types.CreateSubmissionDto, TContext>, 'mutationKey' | 'mutationFn'>): UseMutationResult<Types.SubmissionDto, unknown, Types.CreateSubmissionDto, TContext> {
  const key = saveDraftMutationKey(id);
  
  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);
  
  return useMutation({
    ...options,
    mutationFn: (dto: Types.CreateSubmissionDto) => Client.saveDraft(id, dto),
    mutationKey: key,
  });
}
  
type SaveDraft__MutationParameters = SaveDraftSubmissionQueryParameters & {
  dto: Types.CreateSubmissionDto;
}

/**
 * Save (upsert) draft submission
 */
export function useSaveDraftMutationWithParameters<TContext>(options?: Omit<UseMutationOptions<Types.SubmissionDto, unknown, SaveDraft__MutationParameters, TContext>, 'mutationKey' | 'mutationFn'> & { parameters?: SaveDraftSubmissionQueryParameters}): UseMutationResult<Types.SubmissionDto, unknown, SaveDraft__MutationParameters, TContext> {
  const key = saveDraftMutationKey(options?.parameters?.id!);
  
  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);
  
return useMutation({
  ...options, 
  mutationFn: (data: SaveDraft__MutationParameters) => Client.saveDraft(data.id ?? options?.parameters?.id!, data.dto),
  mutationKey: key,
});
}
  
export function retractSubmissionUrl(id: number): string {
  let url_ = getBaseUrl() + "/api/assignments/{id}/submission/retract";
if (id === undefined || id === null)
  throw new Error("The parameter 'id' must be defined.");
url_ = url_.replace("{id}", encodeURIComponent("" + id));
  url_ = url_.replace(/[?&]$/, "");
  return url_;
}

export function retractSubmissionMutationKey(id: number): MutationKey {
  return trimArrayEnd([
      'SubmissionClient',
      'retractSubmission',
      id as any,
    ]);
}

/**
 * Retract student's own submission (sets state back to Draft)
 */
export function useRetractSubmissionMutation<TContext>(id: number, options?: Omit<UseMutationOptions<Types.SubmissionDto, unknown, void, TContext>, 'mutationKey' | 'mutationFn'>): UseMutationResult<Types.SubmissionDto, unknown, void, TContext> {
  const key = retractSubmissionMutationKey(id);
  
  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);
  
  return useMutation({
    ...options,
    mutationFn: () => Client.retractSubmission(id),
    mutationKey: key,
  });
}
  
type RetractSubmission__MutationParameters = RetractSubmissionSubmissionQueryParameters

/**
 * Retract student's own submission (sets state back to Draft)
 */
export function useRetractSubmissionMutationWithParameters<TContext>(options?: Omit<UseMutationOptions<Types.SubmissionDto, unknown, RetractSubmission__MutationParameters, TContext>, 'mutationKey' | 'mutationFn'> & { parameters?: RetractSubmissionSubmissionQueryParameters}): UseMutationResult<Types.SubmissionDto, unknown, RetractSubmission__MutationParameters, TContext> {
  const key = retractSubmissionMutationKey(options?.parameters?.id!);
  
  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);
  
return useMutation({
  ...options, 
  mutationFn: (data: RetractSubmission__MutationParameters) => Client.retractSubmission(data.id ?? options?.parameters?.id!),
  mutationKey: key,
});
}
  
export function markSubmissionUrl(id: number): string {
  let url_ = getBaseUrl() + "/api/submissions/{id}/mark";
if (id === undefined || id === null)
  throw new Error("The parameter 'id' must be defined.");
url_ = url_.replace("{id}", encodeURIComponent("" + id));
  url_ = url_.replace(/[?&]$/, "");
  return url_;
}

export function markSubmissionMutationKey(id: number): MutationKey {
  return trimArrayEnd([
      'SubmissionClient',
      'markSubmission',
      id as any,
    ]);
}

/**
 * Mark submission (check permission)
 */
export function useMarkSubmissionMutation<TContext>(id: number, options?: Omit<UseMutationOptions<Types.SubmissionDto, unknown, Types.MarkDto, TContext>, 'mutationKey' | 'mutationFn'>): UseMutationResult<Types.SubmissionDto, unknown, Types.MarkDto, TContext> {
  const key = markSubmissionMutationKey(id);
  
  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);
  
  return useMutation({
    ...options,
    mutationFn: (dto: Types.MarkDto) => Client.markSubmission(id, dto),
    mutationKey: key,
  });
}
  
type MarkSubmission__MutationParameters = MarkSubmissionSubmissionQueryParameters & {
  dto: Types.MarkDto;
}

/**
 * Mark submission (check permission)
 */
export function useMarkSubmissionMutationWithParameters<TContext>(options?: Omit<UseMutationOptions<Types.SubmissionDto, unknown, MarkSubmission__MutationParameters, TContext>, 'mutationKey' | 'mutationFn'> & { parameters?: MarkSubmissionSubmissionQueryParameters}): UseMutationResult<Types.SubmissionDto, unknown, MarkSubmission__MutationParameters, TContext> {
  const key = markSubmissionMutationKey(options?.parameters?.id!);
  
  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);
  
return useMutation({
  ...options, 
  mutationFn: (data: MarkSubmission__MutationParameters) => Client.markSubmission(data.id ?? options?.parameters?.id!, data.dto),
  mutationKey: key,
});
}